Correcting tabbing
ROCmSoftwarePlatform/rocSOLVER pull request #147
Opened 2020-09-02 15:31 UTC by saadrahim

2020-09-02 16:53 UTC, cgmb commented
The LLVM style from the last PR wasn't the one we were actually going to use? Oh...

I suppose I will live through this, and on the other end I will come out a stronger person. It's hard now, but years later I will look back and think of how this change built emotional resilience in the face of adversity.

Still, I will never forget that one brief, beautiful, shinning day when the entire repository was formatted with 2-space tabstops and the one true brace style.

2020-09-02 17:00 UTC, cgmb commented
More seriously, I spent most of my professional career with the style you're changing it to. It's not my personal preference, but if we're trying to make it consistent across the organization, I can live with that.

2020-09-02 17:15 UTC, saadrahim commented
I formatted the last PR without our .clang-format file. This .clang-format style was built with feedback from rocBLAS and Tensile developers about a year and half years ago. In the interest of a math libraries wide consistency, it will be nice to have a single standard. @jzuniga-amd did not like the 2 space tabbing (which I do not like as well). I have no stance about braces.

2020-09-02 17:16 UTC, cgmb commented
Sounds good to me, then!

2020-09-02 17:21 UTC, cgmb commented on rocsolver/clients/gtest/getrs_gtest.cpp
> +                                                {10, 10, 2}, // invalid
I spoke too soon. I'd thought we'd caught these sorts of issues in the last PR.

2020-09-02 17:32 UTC, jzuniga-amd commented on rocsolver/clients/gtest/getrs_gtest.cpp
> +                                                {10, 10, 2}, // invalid
Yeah, I think the 

// quick return
{0, 1, 1},                      
// invalid         
{-1, 1, 1},   {10, 2, 10},  {10, 10, 2}, 
// normal (valid) samples
{20, 20, 20}, {30, 50, 30}, {30, 30, 50}, {50, 60, 60}};

solution was only applied by Saad to that particular file we spotted. We may need to extend this to all other gtest files but this can be done in a separate PR.

2020-09-02 17:35 UTC, tfalders commented
This is actually my preferred tabbing and bracing style, so I'm a happy camper.

2020-09-02 17:37 UTC, jzuniga-amd commented on rocsolver/clients/gtest/getrs_gtest.cpp
> +                                                {10, 10, 2}, // invalid
I think we little by little need to change those places where the formatting does "funny" stuff... as we detect them

2020-09-02 21:08 UTC, cgmb requested changes
I've gone through about half the files, so I'll submit my current comments before continuing to the second half. Not all my comments are requests for changes. Some of them are just things we should think about.

2020-09-02 21:31 UTC, cgmb commented on rocsolver/clients/gtest/getrs_gtest.cpp
> +                                                {10, 10, 2}, // invalid
Oh. I didn't see that second part. I've been checking for these cases.

I can switch this to approved and just keep the list of comments if that's what you'd rather, @jzuniga-amd.

2020-09-02 21:56 UTC, saadrahim commented
@cgmb I have to leave for the long weekend now. I would suggest you either 
(1) merge and continue this on another PR
(2) work on my fork to bring this to a desired conclusion

2020-09-02 22:13 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_geqr2.hpp
> -        (ipiv + j), strideP,                          // tau
.

2020-09-02 22:13 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_geqr2.hpp
> -          lda, strideA,                     // leading dimension
.

2020-09-02 22:16 UTC, cgmb commented
I've finished going through the files. We can do whatever @jzuniga-amd wants. Please do enable '[Allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)', just to keep our options open.

2020-09-02 22:40 UTC, jzuniga-amd commented
Up to you Cory!!
We will have to do all these little corrections at some time... I was thinking we can do them on the fly, as we spot them during our developments; but if you have already taken the time to identify most of them, if not all, and you have the stamina to modify all those files... then, well, that would be awesome!

2020-09-02 23:35 UTC, cgmb commented
Ok. I will make the corrections.

There are a few settings I will try tweaking to see if we can avoid some of the silliest changes that clang has made. In other cases, we may just want to write our code in ways that work better with clang-format.

2020-09-11 01:27 UTC, cgmb commented
Sorry this took so long. I've fixed most of these issues in #151. Once that is merged, I'll tweak the format options here to fix as many of the remaining bits that I can, then rebase and reapply.

By the way, why do we have two .clang-format files? And, what version of clang-format should I use on my machine to ensure I'm bug-for-bug compatible with the CI check?

2020-09-11 01:30 UTC, saadrahim commented
[AMD Official Use Only - Internal Distribution Only]

Is it accidentally in two directories? Only one in the root is needed?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Cory Bloor <notifications@github.com>
Sent: Thursday, September 10, 2020 7:28:00 PM
To: ROCmSoftwarePlatform/rocSOLVER <rocSOLVER@noreply.github.com>
Cc: Rahim, Saad <Saad.Rahim@amd.com>; Author <author@noreply.github.com>
Subject: Re: [ROCmSoftwarePlatform/rocSOLVER] Correcting tabbing (#147)

[CAUTION: External Email]

Sorry this took so long. I've fixed most of these issues in #151<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FROCmSoftwarePlatform%2FrocSOLVER%2Fpull%2F151&data=02%7C01%7Csaad.rahim%40amd.com%7C0cdaedc5fc964937cb0508d855f1ec43%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637353844824603924&sdata=%2FqiLkkCI9KXLvjFB36dn7Erz6PLD6wBd15Fi0M84vkQ%3D&reserved=0>. Once that is merged, I'll tweak the format options here to fix as many of the remaining bits that I can, then rebase and reapply.

By the way, why do we have two .clang-format files? And, what version of clang-format should I use on my machine to ensure I'm bug-for-bug compatible with the CI check?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FROCmSoftwarePlatform%2FrocSOLVER%2Fpull%2F147%23issuecomment-690818557&data=02%7C01%7Csaad.rahim%40amd.com%7C0cdaedc5fc964937cb0508d855f1ec43%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637353844824613922&sdata=3dBG8qx7w0%2BPfnMuI7WSaivVf68hX6vpVzueTp2fEBM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTEAR3MW5CTU2T2YFLTYR3SFF4KBANCNFSM4QTEWTPA&data=02%7C01%7Csaad.rahim%40amd.com%7C0cdaedc5fc964937cb0508d855f1ec43%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637353844824613922&sdata=x58Hmb7JtUyh3VaWl6BN3uY7%2Bb9Ix31QCaSTk962%2Brs%3D&reserved=0>.

2020-09-16 20:00 UTC, cgmb commented
#151 is merged, but there was a bit of a problem with the check.

The PR (515d395e14b256c19f9815112a7f9e918c3f1850) was checked with clang-format-11:
http://math-ci.rocm.amd.com/job/compute-rocm-dkms-no-npi-hipclang/job/Static%20Analysis/job/rocSOLVER/job/PR-151/4/display/redirect

The merged result on develop (724b0376627826f0cd73080eaa0229eb0fa04c04) was checked with clang-format-12:
http://math-ci.rocm.amd.com/job/hipclang-bleeding-edge/job/Static%20Analysis/job/rocSOLVER/job/develop/8/display/redirect

Despite the source tree being identical, the former passed the format check while the latter failed. I think this is because clang-format does not guarantee identical formatting between versions, even given the same configuration options.

My suggestion: We should explicitly use `clang-format-10` as our format tool. It's the most recent version of clang-format available via apt-get on Ubuntu 18.04.

2020-09-16 20:04 UTC, cgmb commented
> Is it accidentally in two directories? Only one in the root is needed?

Yes. There's a copy in both [.jenkins](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/6fab03717f64b5df1128d73ce5e8dd1380829602/.jenkins/.clang-format) and the [project root](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/6fab03717f64b5df1128d73ce5e8dd1380829602/.clang-format). I'll remove the former.

2020-09-19 02:44 UTC, cgmb commented
@saadrahim, I'm a little unsure of what to do about clang-format versions. I see now that the version of clang-format we're supposed to use is not from any system package, but rather is the one that ships with ROCm.

I suppose that the clang-format we ship is the obvious choice, but given that the CI that test with multiple versions of ROCm, that inherently means testing against multiple versions, and **[mixing versions is explicitly discouraged by the developers of clang-format](https://reviews.llvm.org/D50078#2056761)**.

To avoid spurious failures in the CI, perhaps we should just disable the format checks on the bleeding edge CI builds.

2020-09-19 02:56 UTC, cgmb commented
I didn't manage to improve everything, but I think it's a lot better. Still not quite finished, as I need to reapply the formatting with the ROCm 3.9 clang-format, and fixup the formatting of the example code... but here's what it looks like after a couple tweaks: https://github.com/ROCmSoftwarePlatform/rocSOLVER/compare/develop...cgmb:fixup-format

2020-09-21 19:42 UTC, cgmb commented on rocsolver/library/src/auxiliary/rocauxiliary_bdsqr.hpp
> +                    A[i + 1 + j * lda] = cs * A[i + 1 + j * lda] - sn * temp;
There's no option to change this in clang-format.

2020-09-21 19:43 UTC, cgmb commented on rocsolver/clients/samples/example_basic.cpp
>  }
I've disabled formatting for the samples.

2020-09-21 19:43 UTC, cgmb commented on rocsolver/clients/common/cblas_interface.cpp
> +             int*                    info);
Still inconsistent. Oh well.

2020-09-21 19:44 UTC, cgmb commented on rocsolver/clients/include/norm.hpp
> +            int*                    incy);
Also still inconsistent, but I did what I could.

2020-09-21 19:44 UTC, cgmb commented on rocsolver/clients/include/norm.hpp
> +    return zlange_(norm_type, m, n, A, lda, work);
This improved a little with tweaked settings.

2020-09-21 19:45 UTC, cgmb commented on rocsolver/clients/include/rocsolver.hpp
> +                         handle, uplo, n, A, lda, stA, info, batch_count);
This seemed to improve a little with the adjusted settings.

2020-09-21 19:46 UTC, cgmb commented on rocsolver/clients/include/testing_bdsqr.hpp
> +        rocblas_status_invalid_pointer);
Was slightly improved with new settings.

2020-09-21 19:47 UTC, cgmb commented on rocsolver/clients/include/testing_bdsqr.hpp
> +        *cpu_time_used = get_time_us() - *cpu_time_used;
I'm not sure I love bin-packing arguments, but it fixes this problem.

2020-09-21 19:47 UTC, cgmb commented on rocsolver/clients/include/testing_gebd2_gebrd.hpp
> +        device_strided_batch_vector<T> dTaup(size_P, 1, stP, bc);
I turned this off.

2020-09-21 19:47 UTC, cgmb commented on rocsolver/clients/include/testing_orgbr_ungbr.hpp
> +        size_t         s = max(hIpiv.n(), 2);
Turned this off.

2020-09-21 19:47 UTC, cgmb commented on rocsolver/clients/include/testing_getrs.hpp
> +        *max_err = err > *max_err ? err : *max_err;
Turned this off.

2020-09-21 19:57 UTC, cgmb approved these changes
Most of the issues previously raised were preemptively fixed in other PRs. I've adjusted the settings slightly to try to fix some of the weirder behaviours I was seeing, and I've rebased and reapplied the formatting to current develop branch.

2020-09-21 20:09 UTC, saadrahim commented
> 
> 
> @saadrahim, I'm a little unsure of what to do about clang-format versions. I see now that the version of clang-format we're supposed to use is not from any system package, but rather is the one that ships with ROCm.
> 
> I suppose that the clang-format we ship is the obvious choice, but given that the CI tests with multiple versions of ROCm, that inherently means testing against multiple versions of clang-format, and **[mixing versions is explicitly discouraged by the developers of clang-format](https://reviews.llvm.org/D50078#2056761)**.
> 
> To avoid spurious failures in the CI, perhaps we should just disable the format checks on the bleeding edge CI builds.

We use the current rocm clang-format to have the same clang-format across all platforms.

The bleeding-edge job throws that the failures as a warning to us so that we can know to update the library prior or shortly after a rocm release.

2020-10-07 21:46 UTC, cgmb commented
@tfalders, @jzuniga-amd, I've resolved the conflicts. We should definitely wait for the CI to run a full set of tests on this one.

2020-10-07 23:35 UTC, cgmb commented
I didn't review every file this time, but I did review a randomly chosen subset. It's not perfect, but it's good enough, I think.

2020-10-07 23:38 UTC, jzuniga-amd approved these changes
LGTM

2020-10-08 00:14 UTC, cgmb commented
The CI appears to be having connectivity problems, but it failed the format check on in the static container. We're testing with both clang-format-11 and clang-format-12, so I've disabled formatting for the things that changed in b73b46abcf32d3946950316fa546964788c6f903.

2020-10-08 00:20 UTC, cgmb commented
It was a trivial change, so I'll wait 20 minutes then merge if there's no alarm bells ringing.

2020-10-08 00:40 UTC, cgmb commented
There's a couple failures from the CI server having troubles accessing resources like docker images, but the full debug mode build succeeded, so I'm going to merge.

2020-10-08 00:41 UTC, merged