Added org2l and orgql
ROCmSoftwarePlatform/rocSOLVER pull request #153
Opened 2020-09-16 22:43 UTC by tfalders

Partially addresses SWDEV-247072

2020-09-17 16:25 UTC, tfalders commented on rocsolver/clients/benchmarks/client.cpp
> +      testing_orgxl_ungxl<double, 1>(argus);
Yes, these booleans determine whether we are testing the blocked code or the unblocked code. Defining an enum to make the behaviour clearer does seem like a good idea, though I'd suggest ROCSOLVER_BLOCKED and ROCSOLVER_UNBLOCKED as the enums instead - there are many functions with blocked and unblocked versions and it would be a hassle to define a separate enum for each one.

That would be beyond the scope of this PR, though - the way it is now is consistent with the current conventions of the library. It's also quite a bit of effort for not much gain.

2020-09-17 16:31 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_org2l_ung2l.hpp
> +      Ap[i + j * lda] = 0.0;
Condition 1 puts ones along the diagonal that goes to the bottom right corner (as opposed to the diagonal from the top left corner, which would be i == j).

Condition 2 zeroes out everything below that diagonal, which would be the lower triangular factor L of the QL factorization.

Condition 3 zeroes out everything on the left side of the matrix (minus the diagonal). This leaves only the k Householder vectors needed to compute Q.

2020-09-17 17:06 UTC, cgmb commented on rocsolver/clients/benchmarks/client.cpp
> +      testing_orgxl_ungxl<double, 1>(argus);
I'd figured it was a local change to client.cpp, but I hadn't realized how many places this ultimately ends up showing up. To be globally consistent, it would need to be done in both the benchmark client.cpp and the gtest.cpp file each functions that would use it...

It's work to change because it is difficult to identify which calls are for blocked versions  vs. unblocked versions just by looking at the code. Otherwise we could do it quite trivially with a find and replace command! But that difficulty also highlights the value of the change in making it easier to read and understand the code based only on local information in a function.

Something to consider for later, I suppose.

2020-09-17 17:23 UTC, cgmb commented on rocsolver/library/src/auxiliary/rocauxiliary_org2l_ung2l.hpp
> +      Ap[i + j * lda] = 0.0;
That makes sense! I think it would be handy to have a short version of that in the function itself. You write code once, but it's read many times.

2020-09-17 17:25 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_org2l_ung2l.hpp
> +      Ap[i + j * lda] = 0.0;
I can do that. I would probably also do the same thing for orgl2 and org2r, since they have similar behaviours.

2020-09-21 19:58 UTC, cgmb approved these changes

2020-09-22 21:53 UTC, jzuniga-amd requested changes
Looks good. Good job!!
A few minor corrections...

2020-09-22 21:53 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_orgql_ungql.hpp
> +  // corresponding left submatrix
You mean the corresponding "bottom" submatrix!

2020-09-22 21:53 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_orgql_ungql.hpp
> +  // start of the unblocked block
Comments could be misleading if not accurate. 
This is not the start of the unblocked part! The unblocked part starts at (0,0)...
kk is the number of householder vectors that will be treated by blocks. So, the unblocked part's size is k - kk, and the first block starts at k - kk

2020-09-22 22:11 UTC, tfalders commented on rocsolver/clients/gtest/orgxl_ungxl_gtest.cpp
> +    {20, 1},
Oops, I think I "fixed" the wrong line. Correcting it now.

2020-09-23 17:19 UTC, jzuniga-amd approved these changes

2020-09-23 17:30 UTC, cgmb commented
:+1:

2020-09-23 17:41 UTC, merged