Added orm2l and ormql
ROCmSoftwarePlatform/rocSOLVER pull request #157
Opened 2020-09-23 18:01 UTC by tfalders

Partially addresses SWDEV-247073

2020-10-05 22:50 UTC, jzuniga-amd requested changes

2020-10-05 22:50 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_orm2l_unm2l.hpp
> +    // insert one in A(i,i) tobuild/apply the householder matrix
Technically, pivots are not on the diagonal but on the (nq-k)-th subdiagonal, ie. A(nq-k+i, i)
Or you can say "insert one in the last nonzero element of the householder vector to build..."

2020-10-05 22:50 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_orm2l_unm2l.hpp
> +    // restore original value of A(i,i)
same here

2020-10-05 23:09 UTC, tfalders commented on rocsolver/clients/gtest/ormxl_unmxl_gtest.cpp
> +  arg.lda = (op[3] == 0 ? arg.M : arg.N) + op[0] * 10;
I must have been thinking in 1-based indexing :D Fixed

2020-10-05 23:24 UTC, jzuniga-amd approved these changes
LGTM!

2020-10-05 23:24 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_orm2l_unm2l.hpp
> +    // insert one in A(nq-k+i,i) tobuild/apply the householder matrix
You know what, I now like the idea of describing with words the elements that are being modified (otherwise the comment just repeat whatever the code says)...

Not a big deal, but I would add:
"insert one in A(nq-k+i,i) -elements along the (nq-k)-th subdiagonal-..." 
or
"insert one in A(i,i) -elements along the diagonal-..."
for the QR case. 

Change it if you have the time.

2020-10-05 23:30 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_orm2l_unm2l.hpp
> +    // insert one in A(nq-k+i,i) tobuild/apply the householder matrix
Oh, I forgot the QR case. I'll add it in now.

2020-10-05 23:41 UTC, cgmb commented on rocsolver/clients/common/cblas_interface.cpp
> +  char transC = rocblas2char_operation(trans);
:+1:

2020-10-05 23:41 UTC, cgmb commented on rocsolver/clients/gtest/ormxl_unmxl_gtest.cpp
> +// if t = 2, then trans = 'C'
I feel like there's gotta be a better way of handling this. Specifying things in this way is really not ideal, but at least it's well-commented.

2020-10-05 23:41 UTC, cgmb commented on rocsolver/clients/include/testing_ormxl_unmxl.hpp
> +  CHECK_HIP_ERROR(dC.memcheck());
Would this be simpler if `device_strided_batch_vector` threw an exception on allocation failure (and didn't consider size=0 an allocation failure)? I actually wrote a version of the rocBLAS containers with that behaviour, but I never got around to actually putting it in a PR. I assume that's what pretty much all our tests are checking for.

2020-10-05 23:41 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +    k                   rocblas_int. k >= 0; k <= m if side is left, k <= n if side is right.\n
Oh, nice. I just noticed this the other day, but it seems you're two steps ahead of me.

2020-10-05 23:41 UTC, cgmb approved these changes

2020-10-05 23:53 UTC, tfalders commented on rocsolver/clients/gtest/ormxl_unmxl_gtest.cpp
> +// if t = 2, then trans = 'C'
This part is heavily (completely?) borrowed from one of the other orm functions. It's a bit cumbersome, but I'm not sure how I would improve it.

2020-10-05 23:55 UTC, jzuniga-amd commented
Ready to go!

2020-10-05 23:58 UTC, tfalders commented on rocsolver/clients/include/testing_ormxl_unmxl.hpp
> +  CHECK_HIP_ERROR(dC.memcheck());
Maybe? I haven't looked at CHECK_HIP_ERROR or memcheck() for a long time, so I can't comment on what improvements could be made. If you want to change anything beyond those two, though, we'll probably be looking at another library-wide change since every test looks like this.

2020-10-05 23:58 UTC, merged

2020-10-06 19:33 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +    lda                 rocblas_int. ldc >= m.\n
Opps. I missed this earlier. Not sure if you want to fix this in #162 or a new PR. The full list of typos:
```
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2126: warning: The following parameters of rocsolver_cunm2l(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, rocblas_float_complex *A, const rocblas_int lda, rocblas_float_complex *ipiv, rocblas_float_complex *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2281: warning: The following parameters of rocsolver_cunmql(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, rocblas_float_complex *A, const rocblas_int lda, rocblas_float_complex *ipiv, rocblas_float_complex *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2056: warning: The following parameters of rocsolver_dorm2l(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, double *A, const rocblas_int lda, double *ipiv, double *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2211: warning: The following parameters of rocsolver_dormql(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, double *A, const rocblas_int lda, double *ipiv, double *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2050: warning: The following parameters of rocsolver_sorm2l(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, float *A, const rocblas_int lda, float *ipiv, float *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2205: warning: The following parameters of rocsolver_sormql(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, float *A, const rocblas_int lda, float *ipiv, float *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2133: warning: The following parameters of rocsolver_zunm2l(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, rocblas_double_complex *A, const rocblas_int lda, rocblas_double_complex *ipiv, rocblas_double_complex *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
/home/docs/rocsolver/rocsolver/library/include/rocsolver-functions.h:2288: warning: The following parameters of rocsolver_zunmql(rocblas_handle handle, const rocblas_side side, const rocblas_operation trans, const rocblas_int m, const rocblas_int n, const rocblas_int k, rocblas_double_complex *A, const rocblas_int lda, rocblas_double_complex *ipiv, rocblas_double_complex *C, const rocblas_int ldc) are not documented:
  parameter 'ldc'
```

2020-10-06 19:44 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +    lda                 rocblas_int. ldc >= m.\n
Good catch! I don't know how I made that mistake. I'll fix it in the currently open PR.