Added gels batched
ROCmSoftwarePlatform/rocSOLVER pull request #164
Opened 2020-10-07 15:08 UTC by cgmb

The core of implementation is in there, but there's a number of questions interspersed. Perhaps you can give me some pointers. I'm still working on the tests.

2020-10-07 22:21 UTC, tfalders requested changes

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                        const rocblas_int batch_count) {
Typename T is usually used to refer to the base type of the array, e.g. float, double, etc...
Typename U is used to refer to the actual array type, e.g. float*, float *const *, etc...
Please add typename U and change A and C to type U.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  if (n == 0 || nrhs == 0 || batch_count == 0) {
Or m == 0

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  hipMalloc(&dIpiv, sizeof(T) * pivot_count_per_batch * batch_count);
ipiv should be allocated in the impl function and passed as a workspace. You'll need to add it to getMemorySize as well.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  constexpr bool STRIDED = false;
These should be passed as parameters to the template function. The impl function can set them to zero if they are not needed.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    T **trfact = (T **)void_trfact_workTrmm;
We usually perform the cast in the function argument list, particularly when the cast is only used once as it is here.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    T **trfact = (T **)void_trfact_workTrmm;
Which will also let you get rid of the extraneous curly braces.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    // what if the result is not success?
If the result is not a success, then you haven't checked the arguments or allocated the workspaces properly. If the algorithm is unsuccessful, that will show up in any info parameters. The zero-on-the-diagonal check in trtrs (which you will need to add) is used to check whether gels will execute successfully, and can be used to set info.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +          handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A,
Why not rocblas_operation_conjugate_transpose?

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +      constexpr bool optimal_memory = true;
optimal_memory should be set in the impl function and passed to the template function.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +#include "../auxiliary/rocauxiliary_ormqr_unmqr.hpp"
Are geqrf and ormqr needed here? Can these includes be removed?

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +    const rocblas_int batch_count) {
Add typename U and change A and C to type U.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +  constexpr bool BATCHED = true;
The rest of the library does not do this. Please remove and use true where you would use BATCHED.

2020-10-07 22:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +  T *scalars = (T *)mem[0];
Declarations of the workspace arrays is done before the declaration of mem, and they are all void pointers. The arrays other than scalars should be declared and assigned as well.

2020-10-07 22:27 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  if (m == 0 || n == 0 || batch_count == 0) {
One more thing: info needs to be set even if you do a quick return. Take a look at potf2 for an example.

2020-10-07 22:28 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  if (n == 0 || nrhs == 0 || batch_count == 0) {
One more thing: info needs to be set even if you do a quick return. Take a look at potf2 for an example.

2020-10-07 22:30 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    const rocblas_int batch_count, T* scalars, void* void_work, void* void_workArr, void* void_diag_trfact, void* void_trfact_workTrmm) {
STRIDED should probably be added as a template parameter as well.

2020-10-08 20:21 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +          handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A,
Oh, I'm guessing you've not been looking at the complex version of the function. Usually, when I implement LAPACK functions in rocSOLVER, I base it off the complex version of the function. This saves time later so that we don't have to go in after the fact to add complex support, and often the only thing I need to do to make it work for the real version as well is to make any conjugations conditional on type T being complex.

2020-10-08 20:37 UTC, tfalders commented
I imagine that we'll be wanting to add the non-batched and strided batched versions of gels to this PR as well, but that's something to discuss with Juan. It should be fairly easy to do once typename U has been added to the template parameters and the shift and stride parameters are passed as arguments to the template function.

2020-10-15 18:56 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +#include "../auxiliary/rocauxiliary_ormqr_unmqr.hpp"
They're required for `rocsolver_geqrf_getMemorySize` and `rocsolver_ormqr_unmqr_getMemorySize`.

2020-10-15 19:01 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +#include "../auxiliary/rocauxiliary_ormqr_unmqr.hpp"
Yeah, but are they needed in the cpp file? Seems like that would be needed only in the hpp.

2020-10-15 19:22 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +#include "../auxiliary/rocauxiliary_ormqr_unmqr.hpp"
Ah. Yeah. You're right! That's duplicated and can be removed.

I originally implemented batched gels in the cpp file. I later moved it to the header as I began changing my implementation to make it consistent with the rest of the library... that incomplete transition from making it work to making it consistent was the source of a lot of the things you've noted in your PR comments, but allowed me to learn one thing at a time rather than dealing with everything at once.

On the bright side, this PR has finally made the structure of the rocSOLVER library code clear to me, so I can just build things consistently from the start going forward...

2020-10-15 19:31 UTC, cgmb commented on docs/source/userguide_api.rst
> +.. doxygenfunction:: rocsolver_sgels_batched
Indeed. Started before that change; finished after. Fixed.

2020-10-15 19:32 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +    by the array of m-by-n matrices A, and the array of n-by-nrhs matricies C.
Fixed... And turned on spellcheck to catch a few other things.

2020-10-15 19:32 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              TODO: why is this seperated into two for just this function?
That makes sense.

2020-10-15 19:33 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +template <bool BATCHED, typename T>
Sure!

2020-10-15 19:38 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +      constexpr bool optimal_memory = true;
Sounds good. My big question is how I should decide whether it should be true or false. I just picked true since optimal sounds good.

2020-10-15 19:42 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +      constexpr bool optimal_memory = true;
So far, we always set it to true, because we always try to allocate the optimal amount of memory. I don't know if or when we'll be revisiting that in the future.

2020-10-16 00:42 UTC, cgmb commented
With the way tests are done, it's difficult to get test coverage of important cases (like parameter validity checks) without having all three implemented, so I will be including the non-batched and strided batched implementations into this PR as well. Originally, I'd thought it would be simpler to just do the one and then iterate on it as necessary, but I was mistaken.

2020-10-28 23:38 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                   size_t *size_3, size_t *size_4, size_t *size_5) {
Done, though this really makes me wish we had a data structure to bundle them all together. That's a lot of names!

2020-10-28 23:40 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +  constexpr bool BATCHED = true;
Done.

2020-11-02 21:48 UTC, tfalders reviewed
It's a vast improvement, but there's more work to be done. Hope these comments are helpful.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +/*! \brief GELS solves batches of overdetermined linear systems defined
overdetermined or underdetermined. If we don't have underdetermined yet, then return rocblas_status_not_implemented from the hpp template and make sure the gtest.cpp file won't create an underdetermined scenario. I imagine that we're going to implement it eventually, so to save on hassle make sure you code everything else under the assumption that we have underdetermined working. Take a look at larfb and larft prior to PR #140 for an example.

Also, this is not the batched version. Remove references to batches or multiple matrices.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +    trans     rocblas_operation. Must be rocblas_operation_none.
Add a description of what trans does. Again, write under the assumption that we will match the functionality of vanilla LAPACK.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +              The number of columns of all matrices C and X in the batch;
I don't think we need to mention X here.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +              On exit, the QR factorization of A from GEQRF.
Instead of 'from', I'd prefer 'as returned by'.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.cpp
> +    const bool optim_mem = true;
Try to match how these are organized and commented in other functions. ATM, it looks quite messy.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.cpp
> +template <typename T>
Add typename U to the template parameters and replace T* with U.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +template <typename T>
Add typename U and replace T* const* with U.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +    const bool optim_mem = true;
Same comment as for non-batched version. strideP should be non-zero since ipiv is not a batched array.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_strided_batched.cpp
> +template <typename T>
Same comment as non-batch version

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_strided_batched.cpp
> +    const rocblas_stride strideP = 0;
strideP should be non-zero since ipiv is not a batched array. It should probably also be separated from the shift parameters.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if(m == 0 || n == 0 || batch_count == 0)
Or nrhs == 0

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        return rocblas_status_invalid_value;
Might need to add cases for transpose in complex case and conj transpose in real case. Again, we should consult Juan.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +       || ldc < n /*|| batch_count < 0*/)
lda < 1 and ldc < 1 are unnecessary. Also, why is batch_count commented out?

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if((n && !A) || (nrhs && !C))
m * n && !A
C will need different cases depending on trans, but for no trans it is m * nrhs && !C.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if(n == 0 || nrhs == 0 || batch_count == 0)
Or m == 0.
You will need to set info to zero before returning if batch_count > 0. See potrf for an example.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A, shiftA, lda, strideA,
Make it conjugate transpose.

2020-11-02 21:48 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                 trfact_workTrmm_invA_arr /*, workArr ? */);
As long as A and B are the same type, I think excluding workArr should be fine.

2020-11-02 22:56 UTC, cgmb commented
Sorry for pinging you. I was just pushing up some intermediate changes and marking things off as I went along. This is currently just a mess of half-finished work. Some bits, such as the commented-out `batch_count` check, are like that because I was verifying that the tests will fail when the code is wrong.

With that said, there are a number of very useful comments in there (such as the empty matrix exceptions to the parameter validity checks, which I'd been wondering about), and I will definitely incorporate your feedback.

When it's done, I'll mark the PR as "Ready for Review" and it will no longer be a draft. I'm working through some issues with my memory allocations...

2020-11-02 23:06 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_strided_batched.cpp
> +    const rocblas_stride strideP = 0;
This may be the cause of my confusion. Thank you.

2020-11-02 23:17 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +       || ldc < n /*|| batch_count < 0*/)
Mmm... Is the lda < 1 / ldc < 1 thing a FORTRAN thing?

2020-11-02 23:18 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if((n && !A) || (nrhs && !C))
I was wondering about that. I thought this was for all empty matrices, but it wasn't obvious from looking at other functions that was the case. Thanks!

2020-11-02 23:22 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                 trfact_workTrmm_invA_arr /*, workArr ? */);
Why does the type need to match?

2020-11-02 23:25 UTC, cgmb commented on rocsolver/clients/include/rocsolver.hpp
> +    (void)stC;
It's a reminder to myself that those variables are unused.

2020-11-02 23:30 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                 trfact_workTrmm_invA_arr /*, workArr ? */);
The rocBLAS template will expect these to be the same type - either batched or strided. When one is strided and the other is batched, we have to match the type, which we do by putting pointers to the strided array in workArr and using workArr instead of the strided array.

2020-11-02 23:35 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +       || ldc < n /*|| batch_count < 0*/)
Possibly. It could also be a small area where we decided to do things differently than LAPACK.

2020-11-03 00:01 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                          rocblas_status_invalid_value)
It would be nice to have the full LAPACK interface, but I've just been tasked with providing parity with CUDA to start with. As I understand it, they don't support those options, so I'm pretty sure it's fine to just stick with `rocblas_operation_none`.

There should definitely be a check that we return a status reflecting that condition, and it's on my todo list before calling this done. The main question I had on that is whether `rocblas_status_invalid_value` is the appropriate status, or if it should be something else.

2020-11-03 00:14 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +    // sizes
Yeah, I wrote these to ensure I covered all the cases, then discovered they were normally tested elsewhere. I can see why it's done that way (we're using a cross-product of inputs and we need test code filter out the invalid ones anyway), and will be deleting these tests.

2020-11-03 20:41 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +/*! \brief GELS solves batches of overdetermined linear systems defined
Note that CUDA only supports the overdetermined case.

2020-11-03 20:48 UTC, tfalders commented on rocsolver/library/include/rocsolver-functions.h
> +/*! \brief GELS solves batches of overdetermined linear systems defined
My understanding is that our plans are to achieve parity with LAPACK. We aren't limited by what is and is not supported by CUDA.

2020-11-03 20:58 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +/*! \brief GELS solves batches of overdetermined linear systems defined
Awesome. This initial work on GELS was just scoped out to help port applications from CUDA to HIP, but I will definitely make sure it's ready for expansion to the full LAPACK interface.

2020-11-04 00:19 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +template <typename T>
I don't understand the reasoning for this. I thought we use U to handle cases where the underlying type could be either `T*` or `T**` (or some const variation thereof). Why template it on U if the type never varies?

2020-11-04 00:28 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +    const bool optim_mem = true;
OpenGL has ruined me. I keep expecting `stride == 0` to mean "tightly packed".

2020-11-04 00:31 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +template <bool STRIDED, typename U>
`U` was actually originally named `T` in the code I started with. `getrf`, I think? I changed it to U when I realized it was not the normal type `T` that we use elsewhere.

2020-11-04 01:25 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if((n && !A) || (nrhs && !C))
I tried to add a test for that case, and realized it's not possible for that first condition to occur, as we only support `m >= n`. If `m == 0`, then it must also be that `n == 0`.

2020-11-04 17:30 UTC, tfalders commented on rocsolver/clients/include/testing_gels.hpp
> +template <bool STRIDED, typename U>
Yeah, I realized while reviewing Juan's PR that this function is handled a little differently. We might want to think about looking at all these bad arg functions and maybe putting U on all of them instead of T.

2020-11-04 17:36 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +template <typename T>
I think there's a good argument to be made that U should not be used in the cpp files, but at the moment it's the library convention and I want to ensure consistency.

2020-11-04 17:43 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if((n && !A) || (nrhs && !C))
This is why I suggest writing most code as if we have the full gels functionality, and only coding differently in the template function and gtest file. There are some assumptions you're baking in that will be easy to miss or forget about when it comes time to implement the remaining functionality.

2020-11-04 18:58 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if((n && !A) || (nrhs && !C))
My strategy has traditionally been the opposite. If you only add code when there exists a test that will fail when it's missing, you can ensure that the tests cover all the cases.

With that said, I came to the same conclusion as you here: I should check m*n for clarity and to help ensure things aren't missed in changes later. In the long-term, though, I hope we may be able to make test improvements that make missing cases more obvious.

2020-11-05 01:01 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +template <typename T>
This is something that really threw me off when I was trying to understand how the library was structured. It felt like a real achievement when I figured out that U was ultimately just a single type in this case. That was the breakthrough that made the overall structure of the library clear to me, when I could contrast them with the functions in the header that actually did require a templated U.

I'm fine with changing this back to U, but I would like to add a task to our backlog to globally replace the unconstrained U template with a typedef that explicitly depends on T and the strided/strided_batched flags. Using a real type definition rather than an (undocumented?) naming convention would make the function's expected inputs more obvious.

2020-11-05 15:37 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  size_t ormqr_scalars, ormqr_work, ormqr_workArr, ormqr_trfact, ormqr_workTrmm;
`geqrf_work` and `ormqr_work` are the same size? I didn't realize that! I only did that for the scalars. I'll be sure to address that before I mark this as resolved.

Rather than pass 'unused', I marked the expression `geqrf_scalars == ormqr_scalars` as an assumption, which in Release mode can be used by the optimizer as a guarantee, and which will be checked for truth in Debug mode (where `ROCSOLVER_VERIFY_ASSUMPTIONS` is defined by default).

When I first added that assumption, I was surprised that it was immediately failing! I hadn't yet implemented the quick return, and so not all my inputs were properly validated yet. I was hitting the quick return on geqrf, but not on ormqr, resulting in differing sizes. That's almost certainly something that I would have caught anyways as I continued to implement the tests, but it was nice to have solid proof that the assertions worked.

2020-11-05 15:45 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +          handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A,
My tests are passing without this change, so something about the test coverage is lacking. This is an easy fix to make, but I don't know how to test it. Do you know?

2020-11-05 15:56 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +// each B_range vector is a {nrhs, trans};
I hadn't written this section yet. It has been entirely reworked.

I replaced the comments with constants, gave the parameters proper types, and defined an Arguments struct for the GELS' parameters. I know that's not entirely consistent with the existing tests, but it shares the same overall structure, even if not the same types.

2020-11-05 16:02 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                 trfact_workTrmm_invA_arr /*, workArr ? */);
I... think I understand what you're saying. I'm sure it will click next time I work with this function. Thanks!

2020-11-05 16:04 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    arg.N = matrix_sizeB[0];
I created a GELS_Arguments class so I could use nrhs for nrhs (among other things).

2020-11-05 16:10 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              The number of columns of all matrices C and X in the batch;
LAPACK includes that tidbit in their docs. I also included it because I appreciated having the reminder.

2020-11-05 17:51 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  size_t ormqr_scalars, ormqr_work, ormqr_workArr, ormqr_trfact, ormqr_workTrmm;
Not work, workArr. Typically, functions have the same workArr size, with some exceptions.

2020-11-05 17:57 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +          handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A,
I'll have to take a look, but if you have tests for the complex cases, then perhaps the imaginary parts of the matrix entries aren't being initialized to be non-zero?

2020-11-05 17:59 UTC, tfalders commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    arg.N = matrix_sizeB[0];
No! We have a single argument class so that command line args to rocsolver-bench can all be assigned to that class. If you start creating new arguments classes, you'll have to map command line args to each class in client.cpp.

2020-11-06 03:05 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    arg.N = matrix_sizeB[0];
Mmm... that's unfortunate. Well, at least the benchmark client seems to clarify which options I should use in the help text. Looking at `Arguments` itself, there's nothing that indicates that `nrhs` should be passed as `K`! You can understand why I was so confused trying to choose the mapping for these tests.

I'll swap it back to the old Arguments class, and pass the parameters as specified documented in the benchmark client. I think the relationships might have been more obvious had the benchmark arguments been left as dynamically typed, and it was up to the individual tests to extract what they needed from it... but that's a discussion for another time.

2020-11-07 00:49 UTC, cgmb commented on rocsolver/clients/common/cblas_interface.cpp
> +                       rocblas_int* lwork)
I copied how `cblas_getri` handled it, though I see `cblas_geqrf` does it differently.

2020-11-09 17:13 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +  size_t ormqr_scalars, ormqr_work, ormqr_workArr, ormqr_trfact, ormqr_workTrmm;
I'm finding that they differ for T=float, m=20, n=20m nrhs=10, batch_count=1. geqrf_workArr is returning 80, while ormqr_workArr is returning 4.

2020-11-09 18:10 UTC, tfalders commented on rocsolver/clients/common/cblas_interface.cpp
> +                       rocblas_int* lwork)
Huh. This might be an error on getri too. Oops!

2020-11-09 18:12 UTC, cgmb commented on rocsolver/clients/common/cblas_interface.cpp
> +                       rocblas_int* lwork)
I'll go ahead and correct both of them in this PR.

2020-11-10 01:49 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    arg.N = matrix_sizeB[0];
I've added a comment to Arguments the rocsolver-bench program documents the parameters.

2020-11-10 01:58 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +template <bool STRIDED, typename U>
I left this as-is. We can revisit this in a sweep of all the tests.

2020-11-10 02:01 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    //    {100, 0}, {150, 0}, {200, 1}, {524, 2}, {1000, 2},
conjugate transpose is not supported yet. Is there any significance to the values of 150 and 524?

2020-11-10 16:47 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        handle, rocblas_side_left, rocblas_operation_transpose, m, nrhs, n, A, shiftA, lda, strideA,
My only question here is how to test this.

2020-11-10 18:29 UTC, cgmb commented
There's some discussion to be had on how best to document cases where we don't support the full LAPACK functionality yet, and I would like to expand the test coverage in our next iteration, but I'm generally happy with this PR now. We'll get the docs sorted out, and I'll swap in whatever is decided on later today. Thank you very much for the guidance, @tfalders.

@jzuniga-amd, the one thing I think is really important to do before merge is to ensure we have test cases that fail when `rocsolver_ormqr_unmqr_template` is called with `rocblas_operation_transpose` rather than `rocblas_operation_conjugate_transpose`.

2020-11-10 22:12 UTC, tfalders commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    ROCSOLVER_ASSUME_X(geqrf_scalars == ormqr_scalars, "GEQRF and ORMQR use the same scalars");
Is this line necessary? ormqr_scalars can instead be named unused.

2020-11-10 22:34 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    ROCSOLVER_ASSUME_X(geqrf_scalars == ormqr_scalars, "GEQRF and ORMQR use the same scalars");
I mean, technically no. This line documents why ormqr_scalars is omitted from the calculation below, and in the debug build, it will check that the belief that that optimization is founded upon is valid.

2020-11-10 22:45 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +namespace B_range { enum { nrhs, trans }; }
This expresses in code what is expressed in comments in other classes. It's even formatted to look almost identical! But, ok. I'll replace it. I don't want to hold up this feature over a trivial change.

2020-11-11 05:07 UTC, jzuniga-amd requested changes
I will review the documentation in rocsolver-functions.h once it is updated.

2020-11-11 05:07 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels.cpp
> +    const rocblas_stride strideP = 0;
strideP is an internal value that only make sense in the context of the template function, it should be calculated inside the template_function body, not passed as a parameter.  

If gels_template() is called from another place in rocsolver (not this implementation), we may not know a suitable value for strideP. Passing an arbitrary value may not be compatible with what the gels algorithm will put inside the array ipiv, which is a workspace array, not part of the API.

See also related comments inside roclapack_gels.hpp below.

2020-11-11 05:07 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels_batched.cpp
> +    const rocblas_stride strideP = std::min(m, n);
See related comments above

2020-11-11 05:07 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels_strided_batched.cpp
> +    const rocblas_stride strideP = std::min(m, n);
idem

2020-11-11 17:53 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    ROCSOLVER_ASSUME_X(geqrf_scalars == ormqr_scalars, "GEQRF and ORMQR use the same scalars");
In this case, it's just an assertion. When reviewing various PRs, it was oven unclear to me why certain variables in the memory calculation were unused. I seem to even recall asking Troy about one in your code and he didn't know either. If I were to read the code without this, I would wonder: "How do you know there's enough room for ormqr to do its work if you didn't actually use all the values returned from its getMemorySize?"

This answers that question with: "I know because GEQRF and ORMQR use the same scalars. (It's the same buffer and thus must be the same size.)"

In debug mode, this condition is checked for validity. It doesn't have a good error message yet, but I plan to continue to improve these checks iteratively.

In release mode, this condition is given to the optimizer as an invariant that can be assumed true without checking, and used to improve code generation. That probably has no relevance to this case, but it will be nice to have this macro in the codebase already for cases in which it does.

This approach caught an error when it was suggested that I should ignore the size of ormqr_workArr. Since it is not necessarily possible to catch out-of-bounds reads or writes via tests, I think trying to catch mistakes in memory allocation early is worthwhile.

There's [a similar macro in Qt with more extensive documentation](https://doc.qt.io/qt-5/qtglobal.html#Q_ASSUME), but in either case, in release mode it's just a wrapper around clang's [__builtin_assume](https://clang.llvm.org/docs/LanguageExtensions.html#builtin-assume).

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              The number of rows of all matrices A in the batch.
the number of rows of matrix A...
this is the non batched version

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              also the number of rows of C.
No, this is not correct!
The number of rows of C depends on whether the system is transposed or not. 
n is just the number of columns of A

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              On exit, the QR factorization of A as returned by GEQRF.
The orthogonal factorization of A as returned by GEQRF or GELQF

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              On entry, the m-by-nrhs matrix C.
Dimensions of C are: m-by-nrhs if non-transposed, or n-by-nrhs if transposed !

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              On exit, the first n rows of each matrix contain the solution vectors.
This is not correct in general. 
We can just say something like:
"On exit, when info = 0, C is overwritten by the solution vectors stored as columns. "

2020-11-11 17:57 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-functions.h
> +              the diagonal element at A(j,j) is 0.
Yes,  the element (j,j) of array A is zero, but this array does not contain matrix A anymore, it has its orthogonal factorization (in other words, the original matrix A could have zeros along the diagonal, but that does not mean it is singular). 

The correct documentation here should read something like:

If info = j > 0, the solution could not be computed because input matrix A is singular; the j-th diagonal element of its triangular factor is zero.

2020-11-11 18:02 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              The number of rows of all matrices A in the batch.
Whoops. I really thought I'd got all those.

2020-11-11 20:07 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                       stream, n, A, shiftA, lda, strideA, info);
That is very informative. I'd assumed trsm handled that itself, but what you're saying makes much more sense. Thanks for the help with this. I'll leave that strtrs comment everything below it in this file untouched to avoid conflicting with your changes.

2020-11-11 20:11 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +        << "Must report error when operation is invalid";
These are printed when the test fails. I wrote them to describe in plain English what requirement the software is not meeting when it fails the test.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +
Rodger.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                          rocblas_status_success)
Added.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                for(rocblas_int j = 0; j < m; j++)
Hmmm.... I copy/pasted this from getrs. I suppose that must operate on square matrices. At some point we should probably pull this into a function where those sorts of parameter differences are more obvious.

It makes no difference to correctness, but this (and getrs) iterate over i and j in the wrong order. That would also be easier to fix globally if it was defined in one place.

In any case. I fixed the correctness issue.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +        err = norm_error('I', m, nrhs, ldc, hC[b], hCRes[b]);
Ok.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +    size_t size_A = size_t(lda) * m;
Fixed.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +        = (m < 0 || n < 0 || nrhs < 0 || m < n || lda < m || ldc < m || ldc < n || bc < 0);
Moved m < n to non-supported values.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +        rocsolver_test_check<T>(max_error, m);
I haven't had a chance to look closely at what the `rocsolver_test_check` does, so please do check that I understood you correctly.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              also the number of rows of C.
Removed.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              On exit, the QR factorization of A as returned by GEQRF.
Fixed.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              On entry, the m-by-nrhs matrix C.
Fixed.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              On exit, the first n rows of each matrix contain the solution vectors.
Changed.

2020-11-11 20:54 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              the diagonal element at A(j,j) is 0.
That makes a lot more sense.

2020-11-11 21:39 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                          rocblas_status_success)
Or rather, added with rocblas_not_implemented as the return value, as this case is not currently possible.

2020-11-11 22:15 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                for(rocblas_int j = 0; j < m; j++)
Hmmm... I'm not understanding something here, because I'm segfaulting on the C host -> device transfer after I replaced the bounds of j with n. I assume I got i and j backwards, but if A is an lda*n array, then shouldn't each n be lda apart? Ugh. Well, I'll revert that change and debug it.

I wish it was easier to see what was actually allocated.

2020-11-12 00:04 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +              On entry, the m-by-nrhs matrix C.
Though, is this not an issue in the brief? I've removed "an n-by-nrhs matrix C" at the top. Maybe take a look at the replacement to ensure I'm not accidentally implying something I shouldn't. I don't speak the same language as mathematicians.

2020-11-12 00:30 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        return rocblas_status_invalid_value;
Done.

2020-11-12 00:31 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    if(m < 0 || n < 0 || nrhs < 0 || m < n || lda < m || ldc < m || ldc < n || batch_count < 0)
Done.

2020-11-12 00:35 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    // note: m >= n
That's already covered by the arg check.

2020-11-12 00:36 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                       const rocblas_stride strideP,
Done.

2020-11-12 00:36 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                                       void* trfact_workTrmm_invA_arr,
Done.

2020-11-12 00:40 UTC, cgmb commented
To do:
- [ ] Update GELS_BATCHED docs
- [ ] Update GELS_STRIDED_BATCHED docs
- [ ] Zero C in quick return
- [ ] Rename C to B
- [ ] Skip TRSM on failed singularity check

2020-11-12 01:41 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        return rocblas_status_success;
Ah. There can be no test case. It's not possible. For `rocblas_operation_none` and `m >= n`, C contains n rows of solutions.

- If `nrhs == 0`, then C is empty.
- If `n == 0` then C is empty.
- If `m == 0` then since `m >= n`, we know `n == 0`.

I'll add a TODO there to remind us of this (though that sort of error should be caught by tests anyway).

2020-11-12 02:11 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                for(rocblas_int j = 0; j < m; j++)
Was calling initData with n and m reversed. Fixed.

2020-11-12 02:36 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    // solve U*X = B, overwriting B with X
Fixed this, because the switch from B to C would make it even more confusing and we probably need a merge for these lines anyway.

2020-11-12 02:46 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    // note: m >= n
Turned this comment into an assertion with a comment to explain why it holds true.

2020-11-12 02:47 UTC, cgmb commented on rocsolver/clients/gtest/gels_gtest.cpp
> +namespace A_range { enum { M, N, lda, ldc }; }
Fixed.

2020-11-12 05:28 UTC, jzuniga-amd commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    {40, 20, 40, 20},
This has nothing to do with the test structure, the test executes whatever you tell it to execute. 

The problem is that if you did not understand that ldb < max(m,n) was invalid, and you were relying on this test to validate your computations, then the test was useless because the code returned invalid_size before executing any operation. 

In other words, what I was asking is to change the test by increasing the value of ldb, not to label it as invalid... you already had a bunch of those.

2020-11-12 05:29 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        return rocblas_status_success;
No, for rocblas_operation_none and m >= n, the size of C is m-by-nrhs!
Its first n rows are computed as the solution of Rx=C (with TRSM), the last m-n rows are a constant residual computed as Q'*C (with ORMQR_UNMQR). As they are constant, they do not intervene in the optimization, but they do exist. 

So, if n=0 (quick return), but m*nrhs != 0, C must be set to zero.
In general, if m*nrhs>0 || n*nrhs >0, C exists and must be set to zero before quick return.

2020-11-12 05:30 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +    // note: m >= n
Ok, that is fine too..

The idea was to have everything ready so that when you complete the functionality, you only substitute _rocblas_not_implemented by your code. As it is right now, when the time come, you will have to change arg check, and add the case-selection logic anyways. Up to you.

2020-11-12 05:30 UTC, jzuniga-amd commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +                       stream, n, A, shiftA, lda, strideA, info);
Unfortunately, this will take more thinking than what I was expected... we cannot simply re-use the mechanism we implemented in GETRI. Let's leave it for now and fix it as a defect in a future PR.

2020-11-12 05:31 UTC, jzuniga-amd approved these changes
Looks good!

2020-11-12 05:49 UTC, cgmb commented on rocsolver/library/src/lapack/roclapack_gels.hpp
> +        return rocblas_status_success;
Oh. It does not contain solution vectors, but it does need to contain residual sums. Got it.

2020-11-12 06:46 UTC, merged