Added sterf and steqr
ROCmSoftwarePlatform/rocSOLVER pull request #178
Opened 2020-11-05 21:43 UTC by tfalders

Addresses SWDEV-247078.

Note that both sterf and steqr have been implemented similarly to bdsqr without any parallelism. steqr is quite slow at the moment. This can probably be addressed by adding some parallelism to lasr.

2020-11-06 00:56 UTC, cgmb commented on rocblascommon/clients/include/utility.hpp
> +                         << ", GPU result=" << GPU_result[j + i * lda] << std::endl;
This adds a buffer flush to the printing of each entry. Is that the intent? It seems like a reasonable change. Just wondering if there's a particular problem you encountered.

2020-11-06 00:56 UTC, cgmb commented on rocsolver/clients/include/testing_steqr.hpp
> +        }
Interesting. So this is an iterative solver? Does n iterations guarantee a solution? Does less than n iterations 
 have a meaningful result? Just personal curiosity.

2020-11-06 00:56 UTC, cgmb commented on rocsolver/library/include/rocsolver-extra-types.h
> +    rocblas_inplace = 212, /**< When not enough memory, this forces in-place computations  */
This breaks binary compatibility, and is going to require bumping the rocSOLVER version to 4.0. Given that it's the reason we're bumping the major version, it will probably need a mention in the changelog.

That's actually rather convenient this time, since it means we'll get to match the ROCm version again, but we should make sure that we've picked values that are not going to require changing again.

2020-11-06 00:56 UTC, cgmb commented on rocsolver/library/include/rocsolver-functions.h
> +    compC     #rocblas_evect.\n
I like these links. I wish it worked for the original rocblas types, too. I'd thought that was going to be a straight-forward extension, as cross-linking the docs is supported in doxygen, but as far as I can tell, there's no existing way to bring that information into sphinx. :(

Though, I hadn't realized until recently that the rocsolver-defined types in the function signature were clickable!

2020-11-06 00:56 UTC, cgmb commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +  BATCH).
Error: Mismatched parentheses!

A trivial typo. I just dressed up as a LISP compiler for Halloween and I still haven't gotten back to normal yet.

2020-11-06 00:56 UTC, cgmb commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +    S b, f, g, anorm, p, r, c, s;
Are all of these used for communication across iterations of the loop, or could some of them be declared within it?

2020-11-06 00:56 UTC, cgmb commented on rocsolver/library/src/auxiliary/rocauxiliary_sterf.hpp
> +    ssfmax = sqrt(ssfmax) / T(3.0);
Great job matching the types. You've done it consistently throughout. 👍

2020-11-06 04:06 UTC, cgmb commented
`rocblas_evect` needs to be added to the types in `userguide_api.rst`

2020-11-06 18:53 UTC, tfalders commented on rocblascommon/clients/include/utility.hpp
> +                         << ", GPU result=" << GPU_result[j + i * lda] << std::endl;
That was the intent, yes. I often print matrices to help me debug problems, and before this change they would be printed after all the test cases printed. It was not only hard to see where one pair of matrices ends and the other begins, but it was also difficult to associate it with the test case that was printing it.

2020-11-06 18:56 UTC, tfalders commented on rocsolver/clients/include/testing_steqr.hpp
> +        }
No, this is multiplying A with each of its n eigenvectors and dividing by the associated eigenvalue. I had to make it an implicit test because eigenvectors are not unique under scaling.

2020-11-06 19:00 UTC, tfalders commented on rocsolver/library/include/rocsolver-extra-types.h
> +    rocblas_inplace = 212, /**< When not enough memory, this forces in-place computations  */
Yeah, this was an iffy change for me. I can change the values back and give the evect enum new values. I wanted to have a nice flow from svect to evect, but if it's not worth breaking compatibility over.

2020-11-06 19:03 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +    S b, f, g, anorm, p, r, c, s;
The ints are used to communicate across all loops. The floats are used across a couple inner loops.

I might do as you suggest for sterf, since I have several floats pulling double duty there and it's a bit confusing.

2020-11-06 19:38 UTC, cgmb commented on rocsolver/library/include/rocsolver-extra-types.h
> +    rocblas_inplace = 212, /**< When not enough memory, this forces in-place computations  */
I hadn't realized this until now, but apparently [the rocblas enum values are supposed to be consistent with other implementations](https://rocblas.readthedocs.io/en/master/functions.html#enums). Is the same true of the rocsolver extra types?

2020-11-06 20:08 UTC, cgmb commented on rocsolver/clients/include/testing_steqr.hpp
> +        }
That's such a good description of what's being done and why. IMO, that would make a great comment to put directly in the code.

2020-11-09 01:28 UTC, jzuniga-amd requested changes

2020-11-09 01:28 UTC, jzuniga-amd commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +        s = g / r;
These computations could, in theory, overflow. Not super important for now, but for consistency, as you are scaling the main algorithm, you should be applying the overflow/underflow scale guards here as well. 
Alternatively, I would suggest that we use the lartg implemented in BDSQR. It is the same thing except that, as mentioned above, it gives you the rotation, not the transpose. That implementation guards against overflow without scaling. 

You should be able to use bdsqr_lartg in STEQR as long as you take the transpose before applying the rotation; I think is easier to modify there, because of the symmetry, rather than in BDSQR.  

(If you agree, I can try and make the modifications along with the correction of the offset in bdsqr_lasr. Ideally we should be using the same Givens-rotations auxiliaries everywhere.)

2020-11-09 01:28 UTC, jzuniga-amd commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +    [ a b ]
This is not BLAS/rocBLAS functionality! 
We should move it to common_device.hpp. 

(Maybe later we can think of better names for these two files: common_device.hpp and rocblas_device_functions.hpp)

2020-11-09 01:28 UTC, jzuniga-amd commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +    [ a b ]
This is not BLAS/rocBLAS functionality!
We should move it to common_device.hpp.

2020-11-09 01:28 UTC, jzuniga-amd commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +/** LASRT_INCREASING sorts an array D in increasing order.
This is not BLAS/rocBLAS functionality!
We should move it to common_device.hpp.

2020-11-09 05:46 UTC, cgmb commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +    [ a b ]
Perhaps we could add a brief comment to the top `rocblas_device_functions.hpp` that describes what sort of functions that should go within it, and maybe also why we have rocblas functionality implemented in a rocsolver header. Even just a sentence or two would help a lot, I think.

2020-11-09 19:09 UTC, tfalders commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +    [ a b ]
I figured it made sense to keep all device functions that implement a full LAPACK or BLAS function in one place, and to have common_device be responsible for other non-LAPACK helper functions. Perhaps we can change the name of rocblas_device_functions to lapack_device_functions? It's up to you - I can certainly move things into common_device.

2020-11-09 19:10 UTC, jzuniga-amd commented
@tfalders I submitted changes to your branch as per comments above. Please merge (if you agree with them) so that they can be reflected here. I will continue my review afterwards.

2020-11-09 20:17 UTC, cgmb commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +            s = 1 / T(std::sqrt(1 + t * t));
I don't think this cast should be necessary. `std::sqrt` takes `T` and returns `T`. If it can be removed, you're better off without it, as having an explicit cast there could potentially hide a mismatched type.

2020-11-09 20:20 UTC, cgmb reviewed
I left one more minor comment, but it's not terribly important. The only thing reason I haven't marked this approved is because that question about our enum values troubles me. It's definitely not something specific to your PR, but since you're adding a new enum, we should figure it out ASAP.

2020-11-09 21:41 UTC, jzuniga-amd commented on rocsolver/library/include/rocsolver-extra-types.h
> +    rocblas_inplace = 212, /**< When not enough memory, this forces in-place computations  */
there are few C/C++ Lapack implementations, and most use chars. If we want, we can follow this [reference](https://bitbucket.org/icl/magma/src/hipMAGMA/include/magma_types.h). Not a bad idea (except for the major version bumping?) 
We can leave it for now and discuss it later; Alternatively we can also add functions that translate otherlibrary_enum -> rocsolver_enum and vice-versa...

2020-11-09 23:37 UTC, cgmb commented on rocsolver/library/include/rocsolver-extra-types.h
> +    rocblas_inplace = 212, /**< When not enough memory, this forces in-place computations  */
This is something we should bring up with @doctorcolinsmith, as breaking binary compatibility would be felt most strongly by the FORTRAN bindings. I think we can accept this PR with `rocblas_evect` as-is, and update everything at once if we choose to do so.

2020-11-09 23:42 UTC, cgmb approved these changes
The `std::sqrt` change is a mere nice-to-have. LGTM.

2020-11-10 17:03 UTC, jzuniga-amd commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +            s = 1 / T(std::sqrt(1 + t * t));
Right, I think the cast could be removed...

2020-11-10 17:21 UTC, tfalders commented on rocsolver/library/src/include/rocblas_device_functions.hpp
> +    [ a b ]
I'll rename the files in a separate PR. Should be possible to automate it, but it will clutter up this PR with extra stuff.

2020-11-10 17:23 UTC, tfalders commented on rocsolver/clients/gtest/steqr_gtest.cpp
> +const vector<vector<int>> large_matrix_size_range = {{192, 192}};
Sure. They'll still be rather small matrices though, since steqr is quite slow at the moment.

2020-11-10 17:26 UTC, tfalders commented on rocsolver/clients/gtest/steqr_gtest.cpp
> +const vector<vector<int>> large_matrix_size_range = {{192, 192}};
Although the slowness could also be due to not having splits in the matrix when compC != N. I'll try out your suggestions for initialization and see how that impacts the runtime.

2020-11-10 17:28 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +        steqr_inf_norm(l, lend, D, E, anorm);
The inf norm is used in vanilla LAPACK for steqr. I wouldn't mind changing it to the max norm if you don't think it will affect the algorithm.

2020-11-10 17:57 UTC, tfalders commented on rocsolver/clients/gtest/steqr_gtest.cpp
> +const vector<vector<int>> op_range = {{0}, {1}, {2}};
I might keep it the way it is just for consistency with the test cases for other functions.

2020-11-10 18:10 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +        steqr_inf_norm(l, lend, D, E, anorm);
I have not checked the LAPACK code. Let me take a look... I don't see why the inf norm will be needed (any option we take should not really affect the algorithm, I think)

2020-11-10 18:20 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +        steqr_inf_norm(l, lend, D, E, anorm);
The only norm that I see in LAPACK steqr is line 269:
anorm = dlanst( 'M', lend-l+1, d( l ), e( l ) )
it is a 'max' norm!

As I said, you can leave the inf norm, but there are some extra FLOPS there that are not really needed. Also, there is the advantage of re-using the code in sterf as mentioned in the other comments

2020-11-10 18:24 UTC, tfalders commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +        steqr_inf_norm(l, lend, D, E, anorm);
Looks like the real versions of steqr use the max norm, but the complex versions use the inf norm. I don't know if there's a reason for that.

2020-11-10 18:35 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +        steqr_inf_norm(l, lend, D, E, anorm);
I don't see why!
D and E are always real, even in the complex case. 
I would prefer to use find_max everywhere. But can always review later. 
(If you can test find_max that would be good)

2020-11-10 22:40 UTC, jzuniga-amd approved these changes
LGTM

2020-11-10 22:40 UTC, jzuniga-amd commented on rocsolver/library/src/auxiliary/rocauxiliary_steqr.hpp
> +    to compute the eigenvalues of a symmetric tridiagonal matrix given by D
STEQR

2020-11-10 22:44 UTC, merged