Fix GESVD for 1x1 matrices
ROCmSoftwarePlatform/rocSOLVER pull request #198
Opened 2020-12-28 18:51 UTC by cgmb

This change fixes the problem described in #197, correcting the GESVD output for V when processing 1x1 matrices.

I've added a test case for GESVD that matched the problem described, but there are probably more tests that should be added (e.g. for ORGBR itself). Given my limited experience in this part of the codebase, perhaps @jzuniga-amd or @tfalders could contribute them, if needed. My branch for this PR is open to edits.

2020-12-29 00:04 UTC, jzuniga-amd requested changes

2020-12-29 00:40 UTC, cgmb commented on rocsolver/clients/include/testing_gesvd.hpp
> +    // where k is 1 for reals and 2 for complex numbers
The 1x1 case has super tight tolerances since we're specifying `tol` as `min(m,n)`. I'm not sure if the inaccuracy is from the actual operation on complex types, or if it is from the calculation of errv, but for some matrices the error is slightly too large to succeed with the original tolerance. There's probably a better way to address the problem, but I was doubling the tolerance to suppress these:

```
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/86, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 2, 2 }) (3 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/87
[       OK ] checkin_lapack/GESVD.batched__double_complex/87 (2 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/88
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/88, where GetParam() = ({ 1, 1, 0 }, { 0, 1, 0, 1, 0 }) (2 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/89
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/89, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 1, 1, 1 }) (1 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/90
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/90, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 3, 0 }) (2 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/91
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/91, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 3, 1 }) (1 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/92
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/92, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 3, 2 }) (2 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/93
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/93, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 0, 3 }) (1 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/94
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/94, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 1, 3 }) (1 ms)
[ RUN      ] checkin_lapack/GESVD.batched__double_complex/95
/src/rocSOLVER/rocsolver/clients/gtest/../include/rocsolver_test.hpp:39: Failure
Expected: (max_error) <= (tol * get_epsilon<T>()), actual: 2.79298e-16 vs 2.22045e-16
[  FAILED  ] checkin_lapack/GESVD.batched__double_complex/95, where GetParam() = ({ 1, 1, 0 }, { 0, 0, 0, 2, 3 }) (2 ms)
```

(As well as identical failures in the `strided_batched` variants.)

2020-12-29 01:23 UTC, cgmb commented on rocsolver/clients/include/testing_gesvd.hpp
> +    // where k is 1 for reals and 2 for complex numbers
I'm not sure whether this is the right model of error for SVD or not, but I think one potential problem may be that if each matrix cell has some random independent error value between 0 and E, then the total error for a 10x10 matrix is almost certainly going to be less than 99\*E, but there's a 1-in-100 chance a 1x1 matrix that the error will be >0.99\*E.

(There's probably a name for this rule, but basically, my thought is basically that larger matrices are more likely to have an error closer to the mean. Even if maximum error does grow linearly, it's far more likely for small matrices to be near that maximum.)

Not sure if that would have any effect on choosing tolerances, but it's just a thought on why adding a test for 1x1 may have introduced some tolerance issues.

2020-12-29 23:44 UTC, cgmb commented
Thanks, @jzuniga-amd. I've incorporated your changes and suggestions. I also changed `rocsolver_test_check` so that it's a little quicker to find the corresponding line in the source code for failing tests, though I can move that to a separate PR if it requires additional discussion.

2020-12-29 23:47 UTC, cgmb commented
There remains a question as to where I should be putting the changelog entry for this bugfix, given that rocSOLVER 3.11.0 has not yet been released. Will this be going into 3.11.0 or the release following that one?

2020-12-30 03:38 UTC, jzuniga-amd commented
Yes, I think that all we can get in before ROCm4.1 feature complete date will go in 3.11.

2020-12-30 03:39 UTC, jzuniga-amd approved these changes
Looks good to me!!

2020-12-30 03:42 UTC, jzuniga-amd commented on rocsolver/clients/include/testing_gesvd.hpp
> +        ROCSOLVER_TEST_CHECK(T, max_error, min(m, n));
you forgot to multiply by 2

2020-12-30 19:09 UTC, cgmb commented
Great. I saw there's another open PR with a CHANGELOG entry, so I'll just follow the existing layout for now to minimize conflicts. We can fixup the headings afterwards.

2021-01-04 17:18 UTC, tfalders approved these changes
LGTM, though I'm curious why rocsolver_test_check has been changed into a macro.

2021-01-04 20:38 UTC, tfalders commented
I've merged in #196. The new test case will probably need to be updated before merging this PR as it uses rocsolver_test_check.

2021-01-04 21:46 UTC, cgmb commented
> LGTM, though I'm curious why rocsolver_test_check has been changed into a macro.

See 2ce50e0bf0878d2e8314a9375276ba65549a2f98

2021-01-05 00:25 UTC, merged