Fix B when GELS info is nonzero
ROCmSoftwarePlatform/rocSOLVER pull request #203
Opened 2021-01-15 22:03 UTC by cgmb

This change is to save and restore B when info is non-zero, to ensure that we only change B iff info is zero. I've looked into some better solutions, but they will probably require some coordination with rocBLAS, and I figure it's better to get a simple fix in now and improve it later.

I don't think GELS has actually been in a release yet, so I suppose this doesn't need a changelog entry.

2021-01-15 23:15 UTC, tfalders reviewed
The testing behaviour in this PR reminds me a lot of the singular tests that were added in PR #168. For consistency, please study one of them (e.g. getri) and adopt a similar style.

2021-01-15 23:15 UTC, tfalders commented on rocsolver/clients/include/testing_gels.hpp
> +            cblas_gels<T>(trans, m, n, nrhs, hA[b], lda, hB[b], ldb, hW.data(), sizeW, &info);
I'd suggest hInfo[b] instead of info.

2021-01-15 23:15 UTC, tfalders commented on rocsolver/clients/include/rocsolver_arguments.hpp
> +    bool rankd = false; // rank deficient
This seems to serve the same purpose as the "singular" field and should be combined with it. It may worth renaming it to something more general, such as "degenerate".

2021-01-15 23:15 UTC, tfalders commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    {40, 20, 40, 40, 1},
There is a fairly new convention for testing degenerate cases that would be a good fit for what you're doing. See getri_gtest.cpp for an example.

2021-01-15 23:20 UTC, cgmb commented
Yeah, I saw getri after finishing and tried to adapt what I'd written to match, though, it seems my adjustments were incomplete. I'll update to match.

2021-01-16 00:03 UTC, cgmb commented
I think it's consistent now.

2021-01-18 17:25 UTC, tfalders requested changes
Almost there. Some small changes to gels_gtest.cpp, and I think it should be good to go.

2021-01-18 17:25 UTC, tfalders commented on rocsolver/clients/gtest/gels_gtest.cpp
>      {40, 20, 40, 40},
The duplicated test cases can be removed. Also, you need to set arg.singular in gels_setup_arguments. You can add an extra value to the test case arrays like you had before to indicate if singular tests are on/off, but you won't need to duplicate any of the cases. Something like this will work:
    {20, 20, 20, 20, 1},
    {30, 20, 40, 30, 0},
    {40, 20, 40, 40, 1},

2021-01-18 17:25 UTC, tfalders commented on rocsolver/clients/gtest/gels_gtest.cpp
> +    {500, 50, 600, 600}, {1000, 500, 1000, 1000},
Add the extra value to enable singular tests here too.

2021-01-18 18:11 UTC, tfalders approved these changes
LGTM!

2021-01-20 18:33 UTC, jzuniga-amd reviewed
Looks good!
Some minor changes. Please also see PR I opened in your branch with other changes that we did not catch in the original GELS PR.

2021-01-20 18:39 UTC, jzuniga-amd commented
Also, you may need a changelog entry as this fix wont be in 4.1 :(

2021-01-21 23:55 UTC, jzuniga-amd commented on rocsolver/clients/include/testing_gels.hpp
> +                    {
to ensure rank deficiency, if m >= n you should introduce a **zero column**; if m < n a **zero row**.

2021-01-26 20:52 UTC, cgmb commented on rocsolver/clients/include/testing_gels.hpp
> +                    {
Upon encountering some failing tests, I swapped the sign figuring I'd somehow got it backwards. (I was actually going to come back and check that before marking your previous comments as resolved.) In any case, you're absolutely right. I've corrected the error.

It might be nice to isolate and test these matrix generators at some point. The outputs they generate are not very visible, but they're important (and unlike a lot of helper code for the tests, the correctness of those outputs doesn't get implicitly tested by the tests they're used in).

2021-01-26 21:24 UTC, jzuniga-amd approved these changes
LGTM

2021-01-26 22:40 UTC, merged