Added sygs2/hegs2 and  sygst/hegst
ROCmSoftwarePlatform/rocSOLVER pull request #211
Opened 2021-02-03 19:52 UTC by tfalders

Addresses ticket SWDEV-247080

2021-02-05 23:33 UTC, doctorcolinsmith requested changes
Recheck this for breaking API changes.

2021-02-05 23:33 UTC, doctorcolinsmith commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
This argument reordering is potentially a breaking change in the API, which we should only do after a deprecation and major version update to ROCm.

Was this template in 4.1?  If so, the argument ordering needs to be preserved.

2021-02-05 23:41 UTC, tfalders commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
The functions in rocblas.hpp are only used internally. They are not exposed in the public API.

2021-02-08 18:58 UTC, cgmb commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
To expand on the design and how we ensure API stability: All public API functions are declared in [library/include](https://github.com/ROCmSoftwarePlatform/rocSOLVER/tree/develop/rocsolver/library/include) and are always C functions.

We do have a private API that includes C++ functions, but it is used only by the rocsolver-test and rocsolver-benchmark clients. We make no promises about its stability (which is why it's private). It does not affect user code that sticks to the documented rocsolver functions.

I think that covers everything. As I understand it, libraries like hipBLAS just use the rocsolver public API, so there's no other interface to worry about. Did I get that right, @tfalders?

2021-02-08 19:05 UTC, cgmb commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
(Note: This function is not a part of the private API, either. It's entirely internal.)

2021-02-08 19:36 UTC, tfalders commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
By private API I assume you mean rocsolver.hpp? I'm not sure private API is how I'd describe it - it's really just a wrapper around rocSOLVER functions for the sake of convenience and is not intended to ever be used in user code.

There's a small handful of functions called by hipBLAS that are not in the public API (i.e. not in library/include), but none of them are affected by this PR. So as far as external libraries are concerned, we should only have to worry about the public API and the handful of cpp files that define these functions.

2021-02-08 20:57 UTC, cgmb commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
> By private API I assume you mean rocsolver.hpp?

No... or at least, not in general. The functions declared in the `extern "C"` block at the top of that file are part of the private API, but I mean all undocumented functions that are marked with `ROCSOLVER_EXPORT`. That includes things like `rocsolver_ostream& operator<<(rocsolver_ostream& os, double x)`.

2021-02-08 21:07 UTC, tfalders commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
Oh, my mistake; I got confused. I see what you mean by private API now. To my knowledge, the private API is used by `rocsolver-test` and `rocsolver-bench` (as you pointed out), the rocSOLVER library (through `rocsolver_ostream`), and the hipBLAS library (through the private functions I mentioned). We don't have any private API functions for hipSOLVER yet, but it's possible that we will have to add some later on too.

2021-02-09 01:04 UTC, doctorcolinsmith commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
For clarification, any item should be considered public if it appears in the ABI as public symbol or is declared in a header file available in the packaged distribution.  It doesn't matter if the intent is to use it for the test clients or not.

2021-02-09 07:00 UTC, cgmb commented on rocsolver/library/src/include/rocblas.hpp
> +                                     rocblas_int lda,
Good to know. That should be fairly straightforward for rocSOLVER to achieve, but we should talk more about it some time.

2021-02-11 02:10 UTC, cgmb approved these changes
:+1:

2021-02-11 04:46 UTC, jzuniga-amd requested changes
Some initial comments and requested changes. I still need to go through the actual algorithms implementations and tests...

2021-02-11 04:46 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +    \brief SYGS2 reduces a symmetric-definite generalized eigenproblem to standard form.
Same here: it is important not to omit the word "real" in "real symmetric-definite" as there could also be a complex symmetric case which, again, is another problem... 
(also applies to all the similar functions below)

2021-02-11 04:46 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +              On entry, the matrix A. On exit, the transformed matrix.
I would like to be more specific here and say: "On exit, the transformed matrix A associated with the equivalent standard eigenproblem" (same for all the other functions below)

2021-02-11 04:46 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +    ldb       rocblas_int. lda >= n.\n
ldb >= n
(same for all the functions below)

2021-02-11 04:46 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +              There is no restriction for the value of strideB. Normal use case is strideB >= lda*n.
strideB >= ldb*n
(same for other similar functions below)

2021-02-11 17:20 UTC, tfalders commented on library/src/include/rocblas.hpp
> +template <typename T, typename U, typename V, std::enable_if_t<is_complex<T>, int> = 0>
Most rocBLAS functions that have symmetric and hermitian variants have separate templates for sy and he - this one, for whatever reason, doesn't. I still separated them to be consistent with the other sy/he functions and just in case the templates are later separated in rocBLAS, but technically we could combine them.

2021-02-11 17:41 UTC, tfalders commented on library/src/lapack/roclapack_sygst_hegst.hpp
> +    T t_minhalf = -0.5;
I'm getting errors from cast2constType when I mark these as const. Also, I'm not sure if the rocBLAS templates accept pointers to constants.

2021-02-12 17:34 UTC, jzuniga-amd requested changes
Looks good to me. Just a few minor additions...

2021-02-12 17:34 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sygst_hegst.hpp
> +    rocblas_int nb = xxGST_xxGS2_SWITCHSIZE;
bs is never used... 

Strictly speaking, there is no switch-size here as, in theory, the complexity of blocked and unblocked algorithm must be the same. So, the only parameter to tune will be the block-size.... 

We may have mixed names in other functions, and all this will change once we start optimizations and tuning. So, not big deal, but if you can eliminate switchsize and make nb=blocksize=64, that will be fine, it will save us some work later.

2021-02-12 19:00 UTC, jzuniga-amd approved these changes
LGTM!!
There is conflict in changelog file. Maybe because I removed the version 3.12.0. Almost certainly it will be the version we release at feature complete day but we don't know yet... we still have some days to break backward compatibility :)-

2021-02-12 19:05 UTC, tfalders commented
Awesome! Conflict should be addressed now. I'll merge after CI passes.

2021-02-12 20:04 UTC, merged