Add Thin-SVD methods
ROCmSoftwarePlatform/rocSOLVER pull request #212
Opened 2021-02-08 06:34 UTC by jzuniga-amd

In-place and out-of-place thin SVD implementation.

(You may notice that in the in-place case, when the leader-dimension vectors will overwrite the matrix A, and no vectors are required on the other side, the initial factorization of A is not really necessary (as this in fact requires some workspace memory). The factorization was included to avoid problems in the unit test, where an extra call to compute the other side vectors will be executed to enable the implicit test).

2021-02-09 00:03 UTC, tfalders requested changes
I'm still reviewing roclapack_gesvd.hpp, but I had some suggestions for the print_device_matrix functions.

2021-02-09 17:07 UTC, jzuniga-amd commented on rocsolver/library/src/include/common_device_helpers.hpp
> +    If uplo = upper, the upper triangular part of A is ketp unchanged **/
fixed

2021-02-09 17:08 UTC, jzuniga-amd commented on rocsolver/library/src/include/common_ostream_helpers.hpp
> +                         const rocblas_int bc = 1,
changed

2021-02-09 17:08 UTC, jzuniga-amd commented on rocsolver/library/src/include/common_ostream_helpers.hpp
> +                         const rocblas_int bc = 1,
changed

2021-02-09 17:18 UTC, jzuniga-amd commented on rocsolver/library/src/include/common_ostream_helpers.hpp
> +    hipMemcpy(AA, A, sizeof(T*) * bc, hipMemcpyDeviceToHost);
I am not sure what you mean here ??

2021-02-09 17:40 UTC, tfalders commented on rocsolver/library/src/include/common_ostream_helpers.hpp
> +    hipMemcpy(AA, A, sizeof(T*) * bc, hipMemcpyDeviceToHost);
I mean you don't need to know the batch_count since you have an index and you're only interested in the matrix at that index. The first suggestion is to read in (idx + 1) pointers, which includes the pointer we're interested in and all the ones preceding it. The second suggestion is better, I think - you would only read in the one pointer at the specified index.

2021-02-09 18:25 UTC, jzuniga-amd commented on rocsolver/library/src/include/common_ostream_helpers.hpp
> +    hipMemcpy(AA, A, sizeof(T*) * bc, hipMemcpyDeviceToHost);
oh I see! Yeah, good idea, no need to copy over all the pointers. I will change it.

2021-02-09 22:57 UTC, tfalders approved these changes
LGTM, though I've had to skim most of the template function since I'm confused by the method.

2021-02-10 16:56 UTC, cgmb commented on library/src/lapack/roclapack_gesvd.hpp
> +    rocsolver_bdsqr_getMemorySize<S>(k, nv, nu, 0, batch_count, &w[1]);
Do you mean in some specific case? I'm not familiar with the problem you're referring to.

2021-02-10 17:04 UTC, tfalders commented on library/src/lapack/roclapack_gesvd.hpp
> +    rocsolver_bdsqr_getMemorySize<S>(k, nv, nu, 0, batch_count, &w[1]);
After looking through some web search results, I may have misunderstood what was meant by pointer to a reference lol. I guess it should be good the way it is.

2021-02-11 00:18 UTC, cgmb approved these changes
Looks good. I had a minor suggestion, but it's not that important.

2021-02-12 00:00 UTC, jzuniga-amd commented on library/src/lapack/roclapack_gesvd.hpp
> +    std::vector<size_t> y(3, 0);
I agree. Changed

2021-02-12 00:00 UTC, jzuniga-amd commented on library/src/lapack/roclapack_gesvd.hpp
> +    *size_diag_tmptr_Y = *std::max_element(y.data(), y.data() + 3);
Ok. Changing this as well.

2021-02-12 00:47 UTC, merged