Use -h to print install.sh help message
ROCmSoftwarePlatform/rocSOLVER pull request #260
Opened 2021-06-01 23:09 UTC by tfalders

install.sh is very unusual in that it uses the -h flag to specify that the library should be compiled using hip-clang, instead of the standard behaviour of printing the help message. Since hip-clang is now the default compiler and the -h flag currently does nothing, I think we should change it to fit the standard behaviour.

2021-06-02 23:06 UTC, cgmb requested changes
There's a reasonable chance that `-h` is still being used in old scripts, and this change will break them.

That's not the worst thing in the world. Compatibility between versions for the build script is just best-effort. We don't have hard compatibility requirements like with the actual code. And the broken scripts will be printing out a help message, so that's a bonus. This would probably help new users more than hinder old ones, so I agree with the change in principle. However, the docs need to updated to match the new behaviour.

2021-06-03 01:29 UTC, tfalders commented
> This would probably help new users more than hinder old ones, so I agree with the change in principle. However, the docs need to be updated to match the new behaviour.

One of the changes I made to https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/257 was to remove examples of `install.sh -h` from the build and install guide. I believe I got all the references to -h, but I can double check later to be sure.

2021-06-03 16:16 UTC, cgmb commented
Sounds good. I should take another look at that PR.

2021-06-03 17:06 UTC, jzuniga-amd commented
I wanted to make this change a long time ago, but at that time CI (CQA and devops) were still using the -h flag to build. If this is not the case anymore (either they are using --hip-clang or nothing), then I see no problems. Maybe @eidenyoshida can confirm?

2021-06-03 20:22 UTC, eidenyoshida commented
The rocm-ci job uses the command below
/install.sh -ricd --hip-clang --install_dir ${ROCM_PATH} --rocblas_dir ${ROCM_PATH}/rocblas | tee -a rocSOLVER.log 

Doesn't seem like there's a -h flag being used

2021-06-03 23:05 UTC, jzuniga-amd approved these changes

2021-06-07 15:57 UTC, cgmb approved these changes
👍

2021-06-07 17:48 UTC, merged