Added potrs
ROCmSoftwarePlatform/rocSOLVER pull request #274
Opened 2021-06-16 22:45 UTC by tfalders

Partially addresses SWDEV-291320.

2021-06-18 18:05 UTC, cgmb approved these changes
I just had a couple comments about rocSOLVER in general. None of them are specific to POTRS.

2021-06-18 18:05 UTC, cgmb commented on library/src/lapack/roclapack_potrs.hpp
> +                                     strideB, batch_count, optim_mem, work1, work2, work3, work4);
This is again not specific to your work here in POTRS, but we should probably start considering the exception-safety of our interface with rocBLAS at some point in the near future.

Right now, if rocBLAS throws an exception from `rocblas_internal_trsm_template`, that exception will not be caught, and will propagate up though the rocSOLVER API. (Which, aside from being contrary to our API documentation, will also leave things like the pointer mode in an inconsistent state, because execution will not reach the end of the function where we restore the handle to its original state.)

It may be that `rocblas_internal_trsm_template` cannot throw an exception, so this is not something we have to worry about. However, if that is the case, rocBLAS should make the promise explicit by marking the functions as `noexcept`.

2021-07-06 14:01 UTC, jzuniga-amd commented on library/src/lapack/roclapack_potrs.hpp
> +                                     strideB, batch_count, optim_mem, work1, work2, work3, work4);
rocblas internal template functions do not throw exceptions. If you want to open a PR in rocBLAS adding the `noexcept`, or bring this to the discussion in rocblas meetings, it would be OK.

2021-07-07 18:38 UTC, jzuniga-amd requested changes
I open PR in your branch with updated tests according to the fix needed for POSV. Please have a look.

2021-07-07 22:59 UTC, jzuniga-amd approved these changes
LGTM

2021-07-07 23:27 UTC, merged