Upgrade to C++17
ROCmSoftwarePlatform/rocSOLVER pull request #276
Opened 2021-06-18 01:08 UTC by cgmb

* Upgrade to C++17

  * It would be better if we could coordinate with rocBLAS to update the C++ standard version across both libraries, but I don't think it's required. I'm not aware of any issues with calling C++14 code from C++17 code, and it works in practice on both Windows and Linux in my testing. It would be possible for rocBLAS to break rocSOLVER by adding code to their internal headers that is valid in C++14 and invalid in C++17, but there's very few such constructs (and we could always send them a fix that's valid for both).

* Add example uses of if constexpr

  * The code changes I made in `common_host_helpers.hpp` and `lib_device_helpers.hpp` were not necessary. I just wanted to use if constexpr in a couple places to show what sort of improvements can be made using C++17 features.

* Suppress HIP warnings

  * C++17 enables a number of additional static checks that the HIP API uses to warn about places where we are not currently checking for errors. These warnings do not refer to new problems, so I'm just suppressing the warnings for now.

2021-06-24 17:23 UTC, cgmb commented
Torre made a good point that it's easier to back out the update if we don't actually start relying on any of the new features immediately. That seemed like a good argument to me, so perhaps I should drop the `if constexpr` commit from this PR.

2021-06-28 12:10 UTC, jzuniga-amd requested changes
I agree!
Also, the places where you changed to use `if constexpr` are not the only cases in the library where this can be used. So good idea to move this to a different PR (where it can be applied everywhere) once we are sure that C++17  won't be backed out.

2021-06-28 18:05 UTC, jzuniga-amd approved these changes

2021-06-30 14:50 UTC, doctorcolinsmith approved these changes

2021-06-30 18:25 UTC, merged