Added posv
ROCmSoftwarePlatform/rocSOLVER pull request #287
Opened 2021-07-08 17:16 UTC by tfalders

Addresses SWDEV-291330.

2021-07-08 19:07 UTC, jzuniga-amd requested changes
Just one little change that I forgot to add here and in POTRS

2021-07-08 19:07 UTC, jzuniga-amd commented on clients/include/testing_posv.hpp
> +    // N/A
You need to verify that uplo != rocblas_fill_full as it is not supported...
This case is tested in badArgs( ) for the gtests, but a user can call rocsolver-bench with uplo=rocblas_fill_full and we must detect it and print corresponding message. See POTF2/POTRF for example. 
(Also, I forgot to add this comment to POTRS. You will need to change it as well)

2021-07-09 16:12 UTC, jzuniga-amd approved these changes
LGTM

2021-07-14 19:12 UTC, cgmb approved these changes
LGTM

2021-07-14 20:06 UTC, tfalders commented
Some CI tests aren't passing because of the trsm bug, but others are so I'm going to go ahead and merge.

2021-07-14 20:06 UTC, merged