Print the runtime version string during tests
ROCmSoftwarePlatform/rocSOLVER pull request #301
Opened 2021-07-29 02:47 UTC by cgmb

rocsolver-test currently prints the versions rocSOLVER that it was built
against. However, it's would be better to print the version that was
queried at runtime, as backwards compatibility allows those to
be different. It's currently a bit confusing when comparing two
implementations of the library via `LD_PRELOAD`.

There's currently no way to know what size of buffer to allocate for
the version string, aside from guessing and checking. In practice,
that works fine, but it's nice to have a more obvious method.

Depends on: https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/815

2021-08-05 21:55 UTC, tfalders requested changes
Looks good, but I have concerns with the approach to the API docs in this PR.

2021-08-05 21:55 UTC, tfalders commented on library/src/common/buildinfo.cpp
> +    *len = std::strlen(VERSION_STRING) + 1;
What's with the +1?

2021-08-05 21:55 UTC, tfalders commented on docs/source/api_otherfunc.rst
> +.. doxygenfunction:: rocsolver_get_version_string_size
This is duplicated in api_loggingfunc. Only one should be kept.

2021-08-05 21:55 UTC, tfalders commented on docs/source/api_loggingfunc.rst
> +-------------------------------
I don't support changing all the header levels in order to accommodate the string functions as a separate section. This will make the API docs for logging inconsistent with all the other API docs.

That's not to say, though, that I oppose putting the new functions on this page. We could combine the logging sections into one. The filename will probably need changing, and I'd prefer the page be titled "Helper and Logging Functions" with the string functions at the top.

2021-08-05 22:01 UTC, cgmb commented on library/src/common/buildinfo.cpp
> +    *len = std::strlen(VERSION_STRING) + 1;
`std::strlen` returns the number of characters in the string, but the API provides the size of buffer to allocate (which should include the null character). For C users, it means the value returned can be passed directly to `malloc` and it will be the right size.

2021-08-05 22:02 UTC, cgmb commented on docs/source/api_otherfunc.rst
> +.. doxygenfunction:: rocsolver_get_version_string_size
I went back and forth on separating them. There's no links to this page... it was supposed to be deleted. Good catch.

2021-08-05 22:13 UTC, cgmb commented on docs/source/api_loggingfunc.rst
> +-------------------------------
I agree. I was trying to leave them unchanged, as I wasn't sure how attached you and Juan were to the existing logging docs layout. Merging them seems good to me.

2021-08-06 06:01 UTC, cgmb commented on docs/source/api_loggingfunc.rst
> +-------------------------------
I partly addressed this. After some thought, I figured maybe we should keep the file name the same. After all, the queries are kinda related to logging (they exist so the information can be logged). When possible, I'd like to avoid renaming files since that changes URLs, so I figure that's close enough it might as well just stay as-is.

I'm also not a big fan of 'Helper' as a descriptor, as it's quite vague. I tried changing it to be more specific. The title might have to change again if we end up with any more oddball functions (unlikely any time soon), but we can cross that bridge when we come to it.

2021-08-06 21:21 UTC, tfalders approved these changes
LGTM!

2021-08-06 21:22 UTC, jzuniga-amd approved these changes
LGTM

2021-08-06 23:44 UTC, merged