Set optim_mem in getMemorySize functions
ROCmSoftwarePlatform/rocSOLVER pull request #303
Opened 2021-07-29 23:27 UTC by tfalders

Per the discussion on https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/291#discussion_r676286511, this PR moves the setting of optim_mem out of the cpp files and into the getMemorySize functions.

2021-07-30 16:52 UTC, cgmb reviewed
Is there a reason to set it false in the quick return case? It seems like it would be slightly simpler to always set it true right at the start of the function.

2021-07-30 17:38 UTC, tfalders commented
> Is there a reason to set it false in the quick return case? It seems like it would be slightly simpler to always set it true right at the start of the function.

It seemed like the appropriate value to set, but I suppose there would not actually be any penalty to setting it to be always true. One of the nice things about the way it is now is you can do a library-wide search for `*optim_mem = true` and easily find all the functions that have to deal with setting it appropriately, but I'm not opposed to changing it.

2021-08-01 22:49 UTC, cgmb approved these changes
LGTM.

> One of the nice things about the way it is now is you can do a library-wide search for *optim_mem = true and easily find all the functions that have to deal with setting it appropriately, but I'm not opposed to changing it.

Sounds like there's pros and cons to both approaches. I have no strong feelings either way, so I'll defer to your judgement.

2021-08-10 22:25 UTC, jzuniga-amd requested changes

2021-08-10 22:25 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sygv_hegv.hpp
> +                                              size_pivots_workArr, size_iinfo, &unused_opt);
`optim_mem` should not be unused...

2021-08-10 22:25 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sygvd_hegvd.hpp
> +                                              size_pivots_workArr, size_iinfo, &unused_opt);
`optim_mem` should not be unused...

2021-08-10 22:59 UTC, tfalders commented on library/src/lapack/roclapack_gesv.hpp
> +    *optim_mem = true;
This is the approach that I was taking initially, until I realized that if one function were to request degraded performance and the other did not, then setting optim_mem in this way would not be appropriate. The clearest solution to this, IMO, would be to have a separate optim_mem for each nested function that calls TRSM, but it's possible that we will take a different approach. Since this is not an issue yet, I figured that I would force optim_mem to be true in these cases with the understanding that it would have to be rethought once we allowed for degraded performance.

2021-08-10 23:11 UTC, jzuniga-amd commented on library/src/lapack/roclapack_gesv.hpp
> +    *optim_mem = true;
The OR would not be appropriate, but I don't see the problem with the AND...

In the end, for these cases where two nested functions call TRSM, for example, the returned workspace size is always the maximum of the two. So if the largest workspace is optimal, then it is so for the smaller one; if the largest workspace is not optimal, then it does not matter whether the smaller is optimal or not, 
`*optim_mem = opt1 && opt2` will be false anyways...

2021-08-10 23:14 UTC, jzuniga-amd commented
> > One of the nice things about the way it is now is you can do a library-wide search for *optim_mem = true and easily find all the functions that have to deal with setting it appropriately, but I'm not opposed to changing it.
> 
> Sounds like there's pros and cons to both approaches. I have no strong feelings either way, so I'll defer to your judgement.

I will also suggest that `optim_mem = true` in those cases with quick-return or when no workspace is needed. If the function does not require a workspace, why do we say "degraded performance"?

2021-08-10 23:28 UTC, tfalders commented on library/src/lapack/roclapack_gesv.hpp
> +    *optim_mem = true;
I was trying to avoid degrading the performance of all nested functions when only one is degraded, but you make a good point. The AND would work as long as I set optim_mem to true in the cases where no workspace is needed, and something like creating separate optim_mem variables could be added on later if it becomes an issue. I'll change it.

2021-08-11 17:36 UTC, jzuniga-amd approved these changes
LGTM

2021-08-11 17:51 UTC, merged