Added sytf2
ROCmSoftwarePlatform/rocSOLVER pull request #311
Opened 2021-08-30 23:39 UTC by tfalders

Addresses SWDEV-291556.

2021-08-31 00:09 UTC, cgmb commented on clients/common/lapack_host_reference.cpp
> +void zsytf2_(char* uplo, int* n, rocblas_double_complex* A, int* lda, int* ipiv, int* info);
This is more a question for Juan, but is the hard-coded Fortran name mangling the reason why we try to default to gfortran in install.sh and CMakeLists.txt? As I understand it, some compilers use different schemes, like making symbols uppercase, rather than just appending an underscore.

2021-09-13 23:19 UTC, jzuniga-amd requested changes

2021-09-13 23:19 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +        A = L D L^T &
It is important to describe how L (or D) is constructed. Especially because, when there are permutations or 2-by-2 pivots, L (or D) is not exactly what is returned in A.
(see lapack documentation for some ideas on how to write this)

2021-09-13 23:19 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +              On exit, the block diagonal matrix D and the multipliers needed to
what are the multipliers? 
We must describe them. See comment above...

2021-09-13 23:19 UTC, jzuniga-amd commented on library/include/rocsolver-functions.h
> +    \brief SYTF2 computes the factorization of a symmetric matrix \f$A\f$
I think we should add "symmetric indefinite matrix" as we are classifying this routine along with potf2/potrf as triangular factorization.

2021-09-13 23:25 UTC, jzuniga-amd commented on clients/common/lapack_host_reference.cpp
> +void zsytf2_(char* uplo, int* n, rocblas_double_complex* A, int* lda, int* ipiv, int* info);
mmm I don't really understand the question. This is the only way I know to call fortran compiled lapack from c/c++ code. If it matters and there are better ways to do it, we can change it, no problem.

2021-09-13 23:26 UTC, jzuniga-amd commented
Some initial comments above...
I am still looking at the kernels.

2021-09-14 19:02 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sytf2.hpp
> +                    // interchange rows and columns k and i (1-by-1 block)
" interchange rows and columns kp = i and kk = k (1-by-1 block)"

2021-09-14 19:02 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sytf2.hpp
> +                    // interchange rows and columns k+1 and i (2-by-2 block)
"interchange rows and columns kp = i and kk = k+1 (2-by-2 block)"

2021-09-14 19:24 UTC, tfalders commented on library/src/lapack/roclapack_sytf2.hpp
> +                info = k;
Good catch! Adding the singular test in has revealed this bug, as well as a couple others that were not caught by the standard test. Working on them now.

2021-09-14 19:32 UTC, tfalders commented on library/src/lapack/roclapack_sytf2.hpp
> +        __syncthreads();
I've tried to remove one of these syncthreads but without success. All the threads in the block need to read sidx[0] and sval[0] only after thread 0 has written to them, but before thread 0 has changed them in the next call to iamax. One approach that could work is creating two separate sidx and sval arrays, but I haven't tried it yet.

2021-09-14 20:05 UTC, tfalders commented on library/src/lapack/roclapack_sytf2.hpp
> +                if(i > 0)
Good catch! Thanks. I must have missed it after I copied the upper kernel to the lower.

2021-09-14 20:56 UTC, tfalders commented on library/src/lapack/roclapack_sytf2.hpp
> +                    {
Splitting the loop is necessary, since the second loop is updating entries that the first loop reads. We need to make sure all the threads finish their reads before the updates begin.

2021-09-15 03:37 UTC, jzuniga-amd commented on library/src/lapack/roclapack_sytf2.hpp
> +                    {
oh, I see, you are right!
Thread j read data that will be updated by other threads.

2021-09-15 20:46 UTC, jzuniga-amd approved these changes
Looks great now...

2021-09-16 22:38 UTC, cgmb approved these changes
LGTM. I had some trivial comments, but that's it.

I'm also happy to see that our internal docs build has improved. The LaTeX is now properly rendered. Hurrah!

2021-09-22 22:58 UTC, merged