Reorg Changes with rocm-cmake wrapper usage
ROCmSoftwarePlatform/rocSOLVER pull request #388
Opened 2022-03-11 18:09 UTC by arvindcheru

- File/Folder Reorg Changes
- Backward Support enabled (rocm-cmake wrapper)
- Replacement of https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/379 with all comments

2022-03-11 18:20 UTC, lawruble13 requested changes
Does the changelog need to be updated?

2022-03-11 18:20 UTC, lawruble13 commented on library/CMakeLists.txt
> +
excess newlines

2022-03-11 18:20 UTC, lawruble13 commented on library/src/CMakeLists.txt
> +	)
Copying files from the source directory to the binary directory should not be done with `rocm_install`. This will attempt to install those header files to the exact build location within the packages as well.

2022-03-11 18:41 UTC, arvindcheru commented on library/src/CMakeLists.txt
> +	)
Thanks for comments, But all source header files are same to be installed and packaged. So this is installing, packaging as expected.

Meantime, this change was also  added to address  incremental changes, build scenario as review comments from @cgmb.

2022-03-11 19:14 UTC, arvindcheru commented on library/src/CMakeLists.txt
> +	)
https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/379#pullrequestreview-897072157

2022-03-11 19:21 UTC, cgmb commented on library/src/CMakeLists.txt
> +	)
I'll look into this issue today. It might take a bit of digging, but I'm sure we can find a solution that satisfies everyone.

2022-03-11 19:21 UTC, lawruble13 commented on library/src/CMakeLists.txt
> +	)
It is still incorrect, by specifying the full destination path all header files will be installed to that location in the package (e.g. if the build directory is `/home/amd/rocSOLVER/build/release`, then this will cause the package to install the header files to `/home/amd/rocSOLVER/build/release/include/rocsolver`.

2022-03-16 03:26 UTC, cgmb approved these changes
There remain some issues to resolve for incremental builds, but we can fix those in the next pass. The release and CI always do clean builds, so the remaining issues are only a problem during development. We can work around the problem by re-running the CMake configure step manually.

That's not ideal, but let's get this merged in so the the integration testing can get going...

2022-03-16 03:26 UTC, cgmb commented on library/src/CMakeLists.txt
> +execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory ${PROJECT_SOURCE_DIR}/library/include ${PROJECT_BINARY_DIR}/include/rocsolver)
We haven't yet resolved the issues with this line, but they're not relevent when you're doing a clean build (which is always the case if you're using `./install.sh`).

2022-03-16 21:38 UTC, jzuniga-amd approved these changes

2022-03-16 22:11 UTC, tfalders approved these changes

2022-03-16 23:13 UTC, merged