Added syevx (Part 1)
ROCmSoftwarePlatform/rocSOLVER pull request #402
Opened 2022-03-30 17:52 UTC by tfalders

This PR adds SYEVX/HEEVX to rocSOLVER. It should be followed later on by a PR to improve performance.

When `erange` is `rocblas_erange_value`, the current implementation will read `nev` from the device onto the host and then iterate over each batch instance to call ORMTR/UNMTR. Ideally, we should create a kernel for ORMTR/UNMTR or allow ORMTR/UNMTR to read size parameters from the device instead, but I'm saving this task for later.

2022-04-04 18:26 UTC, jzuniga-amd requested changes

2022-04-04 19:03 UTC, cgmb commented on clients/include/testing_syevx_heevx.hpp
> +        rocsolver_log_set_layer_mode(rocblas_layer_mode_log_profile);
It also needs to go into the benchmark tests.

2022-04-04 20:17 UTC, tfalders commented on clients/include/rocsolver.hpp
> +        ? rocsolver_ssyevx_strided_batched(handle, evect, erange, uplo, n, A, lda, stA, vl, vu, il,
I figured `abstol` was safe to remove since it has an optimal value and cuSOLVER doesn't include it either, but since you requested it I will add it in.

2022-04-04 20:31 UTC, tfalders commented on clients/include/testing_syevx_heevx.hpp
> +                // check ifail
I'm not sure what you mean. There's a test for ifail when info = 0 and a separate test when info != 0.

2022-04-04 20:32 UTC, tfalders commented on clients/include/testing_syevx_heevx.hpp
> +        rocsolver_log_set_layer_mode(rocblas_layer_mode_log_profile);
Thanks for catching that! I'll add those in.

2022-04-04 20:35 UTC, tfalders commented on clients/include/testing_syevx_heevx.hpp
> +        rocsolver_log_set_layer_mode(rocblas_layer_mode_log_profile);
@cgmb I don't see tests for syev and sygv and their batched versions in the benchmark tests. Is that intentional?

2022-04-04 21:09 UTC, cgmb commented on clients/include/testing_syevx_heevx.hpp
> +        rocsolver_log_set_layer_mode(rocblas_layer_mode_log_profile);
I was working from the function list in `run_function`. It seems there's also the `run_function_limited_precision` to add.

2022-04-04 21:10 UTC, cgmb commented on clients/include/testing_syevx_heevx.hpp
> +        rocsolver_log_set_layer_mode(rocblas_layer_mode_log_profile);
Don't worry about it, then. I'll add the whole lot when I get the chance.

2022-04-05 02:34 UTC, EdDAzevedo commented on clients/include/rocsolver.hpp
> +    return STRIDED
Do you want to use the "if" form to make sure only one branch is evaluated (as done is SYGV_HEGV)?

2022-04-05 02:39 UTC, EdDAzevedo commented on clients/include/testing_syevx_heevx.hpp
> +        for(rocblas_int b = 0; b < bc; ++b)
Have you considered adding OpenMP directives on CPU, something  such as "#pragma omp parallel for"?

2022-04-05 02:46 UTC, EdDAzevedo commented on clients/include/testing_syevx_heevx.hpp
> +    int lwork = !COMPLEX ? 8 * n : 2 * n;
The lapack documentation mentions for optimal efficiency, use a larger value of lwork >= (NB+3)*N. Would the value of lwork affect the performance in this implementation?

2022-04-05 02:53 UTC, EdDAzevedo commented on clients/include/testing_syevx_heevx.hpp
> +    *max_err = 0;
Perhaps you might consider using  a local variable, say "lmax_err" instead of "*max_err", then just before return assign " *max_err = lmax_err;"?

2022-04-05 02:56 UTC, EdDAzevedo commented on clients/include/testing_syevx_heevx.hpp
> +    int lwork = !COMPLEX ? 8 * n : 2 * n;
lapack documentation mentions using a larger value of lwork >= (NB+3) * N for optimal performance. If the code is trying to compare performance, you might consider a larger value of lwork.

2022-04-05 03:00 UTC, EdDAzevedo commented on clients/include/testing_syevx_heevx.hpp
> +        *cpu_time_used = get_time_us_no_sync();
You might consider using OpenMP "#pragma omp parallel for" to use all CPU cores. Is get_time_us_no_sync() returning the elapsed wall clock time or the total cpu time used? The variable name "cpu_time_used" suggests the cpu time used. Perhaps the elapsed time is more relevant, especially if multiple CPU cores are used (by OpenMP or internally by vendor BLAS).

2022-04-05 03:22 UTC, EdDAzevedo commented on library/include/rocsolver-functions.h
> +    info        pointer to rocblas_int. Array of batch_count integers on the GPU.\n
Should there be checking for valid arguments and return info = -i, if the i-th argument is invalid as performed in lapack?

2022-04-05 04:08 UTC, jzuniga-amd commented on clients/include/testing_syevx_heevx.hpp
> +                // check ifail
I meant that if you wanted to have this similar code only once, you could compare `hIfail` directly with `hIfailRes`; their entries must be equal no matter the value of info... 
But now, I think I like better the two separate cases... up to you.

2022-04-05 04:15 UTC, jzuniga-amd commented on clients/include/testing_syevx_heevx.hpp
> +        for(rocblas_int b = 0; b < bc; ++b)
Yes, we have been thinking on adding OpenMP directives not only here but specially in the implicit tests that we have for some functions... the objective would be of course to reduce the execution time of the tests suite (which is growing fast)... 
We want to apply this to all the unit tests, though. So, this should be part of a dedicated separate PR.

2022-04-05 04:20 UTC, jzuniga-amd commented on clients/include/testing_syevx_heevx.hpp
> +    int lwork = !COMPLEX ? 8 * n : 2 * n;
We have not paid much attention to comparing the execution times of our GPU routines and the legacy LAPACK on CPU. We use the LAPACK time just as a reference. But it may be a good idea to see if the LAPACK performance change much if lwork is larger.

2022-04-05 04:35 UTC, jzuniga-amd commented on clients/include/testing_syevx_heevx.hpp
> +        *cpu_time_used = get_time_us_no_sync();
get_time_us_no_sync() returns the time since "epoch". We captured before the API call and then after; then we take the difference to have the wall time (elapsed time) required by the API call. So no, it is not cpu time...

(We don't want to use openMP here as we want legacy LAPACK performance as reference. It may be interesting to compare in the future the performance of an optimized implementation of LAPACK on the CPU, although we know in advance that CPU will be faster in some problems, especially for small matrices).

2022-04-05 05:12 UTC, cgmb commented on clients/include/rocsolver.hpp
> +    return STRIDED
Only one branch will be evaluated. From the C++17 Standard § 8.16 [expr.cond]:

> The first expression is contextually converted to bool. It is evaluated and if it is true, the result of the conditional expression is the value of the second expression, otherwise that of the third expression. Only one of the second and third expressions is evaluated.

With that being said, whatever way we want to structure this is fine by me.

2022-04-05 16:43 UTC, tfalders commented on clients/include/testing_syevx_heevx.hpp
> +                // check ifail
I think there might actually be a bug in how LAPACK's syevx handles its ifail array. The way it updates ifail when sorting the eigenvalues & vectors doesn't look correct to me, so I did ours differently. If info != 0, `hIfail` and `hIfailRes` won't be equal.

2022-04-05 16:49 UTC, tfalders commented on library/include/rocsolver-functions.h
> +    info        pointer to rocblas_int. Array of batch_count integers on the GPU.\n
Currently, the library convention is to not do this, and adding it in would be a library-wide change that would require some method signature changes (and thus deprecations). If an argument is invalid, we use the returned status to indicate what kind of invalid argument was detected. Unfortunately, the index of the argument is not provided.

2022-04-05 16:54 UTC, tfalders commented on clients/include/testing_syevx_heevx.hpp
> +    *max_err = 0;
If we were to make this change, for the sake of consistency I would want to make the same change across all of our tests. That goes beyond the scope of this PR, and I'm not sure the effort would really be worth it.

2022-04-06 19:06 UTC, cgmb approved these changes
I'm not sure why the Windows tests didn't trigger, but I've manually started them. Given that there are known test failures on Windows right now, I've downgraded the Required tests to just the build stage.

2022-04-07 17:29 UTC, tfalders commented
> Perhaps the code in "getPerfData" (around line 412) should be updated too?

Ah, you're right! Silly me. Thanks for catching that!

2022-04-07 20:22 UTC, merged