Added syevj
ROCmSoftwarePlatform/rocSOLVER pull request #427
Opened 2022-05-19 18:41 UTC by tfalders

syevj calculates eigenvalues and eigenvectors by the iterative Jacobi method.

2022-05-20 23:39 UTC, tfalders commented
It seems there is a bug with the complex case. I will close for now and re-open once it's fixed.

2022-05-31 13:44 UTC, EdDAzevedo commented on clients/include/testing_syevj_heevj.hpp
>      int lwork = (COMPLEX ? 2 * n - 1 : 0);
Should lwork == 0? Perhaps it should be  say something like

int const lwork = (COMPLEX) ? 2*n-1 : 3*n-1 ; 


The lapack documentation also says setting a larger value  lwork >= (NB+2)*N for higher performance.

2022-06-01 03:46 UTC, cgmb commented on library/src/include/lib_device_helpers.hpp
> +
What do you think about `magnitude` and `magnitude_sq`? Or `abs` and `abs_sq`? I will freely admit that 90% of my math background is working in real vector spaces, so I don't have a great feel for complex vocabulary. Still, `length` feels weird.

2022-06-01 13:09 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +
If this is not performance critical, you might consider scaling the real part and complex part  to avoid numerical overflow. 

Maybe something like

auto  hypot = [](double const  a, double const b) -> double {
  // evaluate  sqrt( a*a + b*b)  as  abs(a) * sqrt( 1 + (b/a)*(b/a) ) or
  //   abs(b) * sqrt( (a/b)*(a/b) + 1 )

   double ans = 0;
   if ((a == 0) && (b == 0)) { return( 0 ) };

   double const abs_a = (a > 0) ? a : (-a); 
   double const abs_b = (b > 0) ? b : (-b);

   if (abs_a > abs_b) {
      double const c = abs_b/abs_a;  
       ans = ( abs_a * sqrt( 1 + c * c ) );
      };
   else {
      double const c = abs_a/abs_b;
       ans = ( abs_b * sqrt( 1 + c * c ) );
    };
 return( ans );
}

2022-06-03 22:54 UTC, cgmb commented on clients/benchmarks/client.cpp
> +            "                           ")
This should probably be added to the benchmark tests.

2022-06-06 17:19 UTC, tfalders commented on clients/benchmarks/client.cpp
> +            "                           ")
Aren't the parameters in the benchmark tests all `char`s? I don't see any tests for numeric parameters like `max_sweeps`.

2022-06-06 17:22 UTC, tfalders commented on library/src/include/lib_device_helpers.hpp
> +
Sure, I can change it to `magnitude` and `magnitude_sq`. I'll also take a look at doing the proposed scaling - if it doesn't have a noticeable impact on the performance, I'll make the change.

2022-06-06 17:33 UTC, jzuniga-amd commented on library/src/include/lib_device_helpers.hpp
> +
Yes, `abs` is the right name for these helpers, although I don't see why you are re-writing this functionality. rocblas_complex have `abs` implementations which guards against overflow as Ed suggested (see https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/f6730d8614fa2a23b4c1402eb6c626197bf36cbf/library/include/internal/rocblas-complex-types.h#L481)

I think rocBLAS is injecting its `abs` into std, but anyways, since we switched to c++11 `std::abs` (being rocblas or not) should give you the magnitude or modulo of any number (real or complex)

2022-06-06 19:11 UTC, tfalders commented on library/src/include/lib_device_helpers.hpp
> +
Oh, interesting! I didn't realize rocBLAS had this functionality. Originally, I was using rocSOLVER's `aabs` function, which does not call `abs` but `asum`. I guess I can call `abs` directly and it should work.

2022-06-06 20:57 UTC, cgmb commented on library/src/include/lib_device_helpers.hpp
> +
> I think rocBLAS is injecting its abs into std, but anyways, since we switched to c++11 std::abs (being rocblas or not) should give you the magnitude or modulo of any number (real or complex)

We really should get them to change that, because

> It is undefined behavior to declare a full specialization of any standard library function template. (since C++20)

https://en.cppreference.com/w/cpp/language/extending_std

Frankly, I find it very confusing anyways. What even provides the `__device__` implementations of `std::abs` and `std::norm` for real values?

2022-06-06 21:30 UTC, cgmb commented on clients/benchmarks/client.cpp
> +            "                           ")
Ah. Yeah, that's fine. I suppose the function itself is in the limited precision list too, which is still on the todo list.

2022-06-07 02:55 UTC, cgmb commented on library/src/include/lib_device_helpers.hpp
> +
Looking closer, those aren't even specializations. They're just new definitions added to the std namespace, so I think that falls under:
> It is undefined behavior to add declarations or definitions to namespace std or to any namespace nested within std

2022-06-07 04:13 UTC, jzuniga-amd requested changes

2022-06-07 04:13 UTC, jzuniga-amd commented on library/src/lapack/roclapack_syevj_heevj.hpp
> +            __syncthreads();
This barrier and all the other syncs in this kernel only synchronizes the threads within the same thread-group. In other words, when n>512 (as BS1=256), at this point you will have threads belonging to different groups and they wont be synchronized; there is no guarantee that this kernel will work... (see two consecutives runs below)

>> $$./clients/staging/rocsolver-bench -f syevj -n 515 -v 1 --iters 1
============================================
Arguments:
============================================
evect           uplo            n               lda             abstol          max_sweeps
N               U               515             515             0               100
============================================
Results:
============================================
cpu_time_us     gpu_time_us     error
29503           1367509         _**1.4387098860657362e+16**_

>> $$./clients/staging/rocsolver-bench -f syevj -n 515 -v 1 --iters 1
============================================
Arguments:
============================================
evect           uplo            n               lda             abstol          max_sweeps
N               U               515             515             0               100
============================================
Results:
============================================
cpu_time_us     gpu_time_us     error
29547           21505279        _**0**_

2022-06-07 04:13 UTC, jzuniga-amd commented on library/src/lapack/roclapack_syevj_heevj.hpp
> +            __syncthreads();
threads from different groups are not synchronized. One group could start working with a column/row that is still being modified by another group! 
This design needs to be modified...

2022-06-07 04:19 UTC, jzuniga-amd commented on library/src/include/lib_device_helpers.hpp
> +
This may be a work to be done in conjunction with the rocBLAS team. We have been using `std::abs` in all other rocsolver functions... I don't know whether it is calling the original `abs` in the standard library, or the rocBLAS implementation, but it's working OK. For now let's just don't add more helpers for the same functionality.

2022-06-07 17:27 UTC, tfalders commented on library/src/lapack/roclapack_syevj_heevj.hpp
> +            __syncthreads();
How in the world did I forget that? Thanks, I'll take care of it right away.

2022-06-20 17:47 UTC, jzuniga-amd approved these changes
LGTM. Thanks Troy!
(Performance gain of this first implementation was not as good as predicted but it produces correct results. We'll merge as feature complete is approaching. A round of optimizations will follow in a different PR later)

2022-06-20 22:51 UTC, cgmb approved these changes

2022-06-21 17:06 UTC, merged