Implement lauum
ROCmSoftwarePlatform/rocSOLVER pull request #490
Opened 2022-12-13 16:49 UTC by qjojo

This adds lauum to rocSOLVER, which computes U*U^T or L^T*L for real triangular matrices, or U*U^H or L^H*L for complex triangular matrices. 

Currently the complex tests are notched out because the trmm call in rocauxiliary_lauum.hpp is producing invalid results for the complex case for reasons that I can't figure out, the same call works in the real case and the requested operation is `rocblas_operation_conjugate_transpose`, so there's either a bug in rocBLAS or I'm missing a gotcha in the way trmm is being called.

2022-12-13 18:55 UTC, cgmb requested changes
This is a public API function, right? You've added the Doxygen descriptions, but you'll need to edit the Sphinx docs in `docs/sources` to add it to the human-readable documentation.

2022-12-13 18:55 UTC, cgmb commented on clients/include/lapack_host_reference.hpp
> +                 rocblas_int inc);
s/cblas/cpu/

2022-12-13 18:55 UTC, cgmb commented on clients/include/testing_lauum.hpp
> + * Copyright (c) 2020-2022 Advanced Micro Devices, Inc.
Is there any code in here from 2020? If not, just 2022.

2022-12-13 18:55 UTC, cgmb commented on clients/include/testing_lauum.hpp
> +#include <iostream>
This looks unnecessary.

2022-12-13 19:03 UTC, qjojo commented on clients/include/testing_lauum.hpp
> +#include <iostream>
Leftover from debugging, removed

2022-12-13 19:25 UTC, tfalders reviewed
Not bad for a first attempt at adding a new function, though there are some issues to address, namely the failing complex tests and a potential segfault in the implementation.

Also, you need to add the new functions to the documentation. The changelog needs to be updated, as well as userguide_intro.rst and api_auxiliaryfunc.rst.

2022-12-13 19:25 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_lauum.cpp
> +    return rocsolver_lauum_template<T>(handle, uplo, n, A, shiftA, lda, info, strideA, batch_count,
Why is `strideA` after `info`? Though I suppose it doesn't matter if we're removing `info`.

2022-12-13 19:25 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +    dim3 threads(32, 32);
32 should be replaced by BS2 (the 2D thread-block size defined in ideal_sizes.hpp)

2022-12-13 19:25 UTC, tfalders commented on clients/gtest/lauum_gtest.cpp
> +    {30, 30}};
lda should be larger than n in some cases

2022-12-13 19:25 UTC, tfalders commented on clients/gtest/lauum_gtest.cpp
> +*/
All functions in the API should be tested. We should either get the complex tests working, or remove the complex cases from the API until the tests are working.

2022-12-13 19:25 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +                            work, shiftA, lda, strideA, no_mask{}, uplo);
work should not be using the same values as A in this case. In particular, if `lda > n`, you should expect a segfault. For work, use shiftA -> 0, lda -> n, strideA -> n * n (or define ldw = n, strideW = n * n).

Also applies to trmm and kernel calls below.

2022-12-13 19:25 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +    }
I'd prefer if this was condensed using the ( ? : ) notation.

2022-12-13 20:36 UTC, qjojo commented on clients/gtest/lauum_gtest.cpp
> +*/
I changed the error tolerance as you suggested but the complex cases are still failing. I'll remove the complex versions from the public API and docs so I can get this in.

2022-12-13 23:17 UTC, tfalders approved these changes
LGTM! Be sure to wait for Juan's approval before merging, and do a squash-and-merge.

2022-12-13 23:47 UTC, cgmb reviewed
I'm picking on the wording a bit, but it looks good.

2022-12-13 23:47 UTC, cgmb commented on library/include/rocsolver/rocsolver-functions.h
> +    For complex types computes \f$AA^H\f$ or \f$A^HA\f$ depending on uplo.
Just to pick on the wording here a bit:

- Every other function uses the phrasing "If uplo indicates upper".
- "if uplo denotes lower then \f$A^TA\f$ is computed instead" is an independent phrase, so there's a comma splice here. Maybe just make it an independent sentence. It's also missing a comma before "then".
- The description for complex types is inconsistent in style compared to the description of the real functions. Given that we're not including the operations on complex types at the moment, I think the description of the operations on complex types can be dropped for now.

2022-12-14 00:04 UTC, cgmb approved these changes

2022-12-14 07:31 UTC, jzuniga-amd reviewed
Looks good for initial implementation, good job.  We may need to revisit it soon for optimizations, though. I was hoping for an implementation along the lines of a blocked algorithm (with gemms and symmetric rank updates)... the current implementation has too many data movements; it will probably not show the performance expected by the group requesting the API. We will see.

Just a few minor comments that require attention:

2022-12-14 07:31 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +    rocblasCall_trmm<false, true, T>(handle, side, uplo, rocblas_operation_conjugate_transpose,
Not the best use of TRMM. work is also triangular and being size n-by-n, conceptually, half of the operations of the whole product are multiplications by zero!

2022-12-14 07:34 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +    rocblasCall_trmm<false, true, T>(handle, side, uplo, rocblas_operation_conjugate_transpose,
we will revisit this in the optimization round

2022-12-14 17:26 UTC, jzuniga-amd approved these changes

2022-12-14 18:06 UTC, qjojo commented
CI failure is the known issue with managed malloc, I will manually merge after consulting the rest of the team.

2022-12-14 18:07 UTC, merged