Enable [cz]lauum
ROCmSoftwarePlatform/rocSOLVER pull request #510
Opened 2023-01-11 17:41 UTC by qjojo

This changes lauum to use syrk/herk as the kernel to provide better performance and accuracy than trmm. Also enables support for complex numbers.

2023-01-11 20:03 UTC, cgmb submitted a review, later dismissed
You've partially updated the clients, but the tests still need to be updated to run these.

2023-01-12 22:11 UTC, tfalders submitted a review, later dismissed
CI is failing for the real upper triangular cases.

2023-01-25 19:34 UTC, EdDAzevedo approved these changes

2023-02-01 19:13 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +                                        U work)
It's better for `work` to be a `T*` or a `void*`. Auxiliary functions don't have batch versions, but they can be called by batched functions behind the scenes. If `U` is `T* const*`, then we'll have to set up `work` as a batched array, which is a pain.

2023-02-07 19:48 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +                                        U work)
Yes, this is important and needs to be changed.

2023-02-07 19:51 UTC, jzuniga-amd submitted a review, later dismissed

2023-02-07 19:51 UTC, jzuniga-amd commented on clients/common/testing_lauum.cpp
> +INSTANTIATE(TESTING_LAUUM, FOREACH_SCALAR_TYPE, APPLY_STAMP)
You also need to put `lauum` in the map with no limited precision in 
`clients/include/rocsolver_dispatcher.hpp`. Otherwise you wont be able to run `lauum` with complex precision with the rocsolver_bench client.

2023-02-07 19:52 UTC, jzuniga-amd commented on clients/common/testing_lauum.cpp
> +INSTANTIATE(TESTING_LAUUM, FOREACH_SCALAR_TYPE, APPLY_STAMP)
complex tests are still failing everywhere. I will have a look.

2023-02-07 19:53 UTC, jzuniga-amd commented
the complex tests are still failing... I will have a look.

2023-02-07 23:00 UTC, qjojo commented
Juan determined that the CPU implementation of lauum is incorrect, so I changed the test cases to evaluate it directly instead. All tests should pass now.

2023-02-08 01:38 UTC, EdDAzevedo commented
There may be an implicit assumption that the matrix A is Hermitian where conceptually   conj(transpose(A)) == A, even though only the upper or lower triangular part is accessed. Thus there might be an implicit assumption that the diagonal entries of matrix are also  "real" numbers (imaginary part is exactly zero).   So another work around is to set the diagonal entries of the matrix to be real numbers (not complex numbers or to have the imaginary part of the diagonal entries to be exactly zero).   Just a thought.

2023-02-10 18:35 UTC, jzuniga-amd commented on clients/include/testing_lauum.hpp
> +template <typename T, typename Td, typename Th, bool COMPLEX = rocblas_is_complex<T>>
not really important, but the macro COMPLEX is not needed anymore.

2023-02-10 18:52 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_lauum.hpp
> +                                        void* work)
Just for consistency, in the .cpp file you better call `rocsolver_lauum_template` with `(T*)work`, and I would define `work` here as `T*` instead of `void` and casting every time I use it in the body of the function. 

In general, the way we use the typenames across the library is:
`T`: defines the base precision (float, double, float_complex or double_complex). Normally passed explicitly when calling the template functions.
`U`: could be either a pointer to `T` (`U = T*`) for the normal and strided_batched cases, or an array of pointers to `T` (`U = T* const []`) for the batched cases. `U` is normally inferred. 
S: some functions mix real and complex arrays. In this cases, `S` defines the base real precision (ie. `S` is float when `T` is float or float_complex, for example). `S` is normally inferred.

2023-02-10 19:13 UTC, jzuniga-amd commented
Also don't forget to update the documentation and changelog to reflect that LAUUM supports complex now.

2023-02-10 19:17 UTC, jzuniga-amd commented
And we should be more explicit in the documentation with the fact that the triangular factors in the computations are expected to come from a symmetric/hermitian matrix.

2023-02-13 17:52 UTC, jzuniga-amd requested changes
Please look at PR in your branch for documentation updates.

2023-02-15 01:53 UTC, jzuniga-amd approved these changes
LGTM

2023-02-15 05:27 UTC, cgmb approved these changes

2023-02-15 16:23 UTC, tfalders approved these changes
Looks good! Very minor issue to correct.

2023-02-15 16:23 UTC, tfalders commented on clients/common/lapack_host_reference.cpp
> +             int* ldb);
Minor issue, but m should come before n, right?

2023-02-15 16:23 UTC, tfalders commented on clients/common/lapack_host_reference.cpp
> +}
Same as above

2023-02-15 16:23 UTC, tfalders commented on clients/include/lapack_host_reference.hpp
> +               rocblas_int ldb);
Same as above

2023-02-15 17:23 UTC, qjojo commented
The CI failures are unrelated to the changes in this PR, I will force squash and merge.

2023-02-15 17:24 UTC, merged