Improve error reporting for info test failures
ROCmSoftwarePlatform/rocSOLVER pull request #517
Opened 2023-01-20 03:43 UTC by cgmb

The rocsolver tests report certain error conditions (like unexpected info values) by adding 1 to the measured error. This can make it difficult to understand what is wrong when reviewing the logs for a failed set of tests (especially when there are multiple properties that could all increment the error).
    
The Google Test `EXPECT_` functions will check a condition, but allow the test to continue. This means that an error can be recorded at the place where it occurs, without losing data.

The macros are defined to nothing for rocsolver-bench, so this additional error output is only emitted in rocsolver-test.

2023-01-25 22:17 UTC, jzuniga-amd reviewed
Looks good to me, I just wonder why not all functions that report `info` are getting similar assertions. For example, getf2/getfr, gels, getri, stedc, steqr, potf2/potrf, and many others also return some type of `info` parameter.

2023-01-25 22:25 UTC, cgmb commented
I found these checks by searching for `err += 1`, so I may have missed info checks that didn't use that pattern. I'll expand it to include those as well.

2023-01-26 21:38 UTC, cgmb commented
This is some example output in a case where I've forced a failure by setting all elements of hInfoRes to 125:
```
[ RUN      ] checkin_lapack/TRTRI.strided_batched__double_complex/17
/home/cgmb/rocSOLVER/clients/include/testing_trtri.hpp:193: Failure
Expected equality of these values:
  hInfo[b][0]
    Which is: 0
  hInfoRes[b][0]
    Which is: 125
where b = 0
/home/cgmb/rocSOLVER/clients/include/testing_trtri.hpp:193: Failure
Expected equality of these values:
  hInfo[b][0]
    Which is: 0
  hInfoRes[b][0]
    Which is: 125
where b = 1
/home/cgmb/rocSOLVER/clients/include/testing_trtri.hpp:193: Failure
Expected equality of these values:
  hInfo[b][0]
    Which is: 0
  hInfoRes[b][0]
    Which is: 125
where b = 2
/home/cgmb/rocSOLVER/clients/include/testing_trtri.hpp:442: Failure
Expected: ((max_error)) <= ((n)*get_epsilon<T>()), actual: 3 vs 2.22045e-14
```

2023-01-26 21:42 UTC, cgmb commented
Added checks for all functions that use `err++` or `err = 1`. I think this is once again ready for review, so please take another look when you have a moment.

2023-01-30 19:59 UTC, cgmb commented
For a more concrete example, these are the current Windows failures we've been seeing in PRs for the past while:
```
[ RUN      ] checkin_lapack/BDSVDX.__double/139
C:/workspace/clients/include\testing_bdsvdx.hpp(225): error: Expected equality of these values:
hNsv[0][0]
Which is: 1
hNsvRes[0][0]
Which is: 0
C:/workspace/clients/include\testing_bdsvdx.hpp(528): error: Expected: ((max_error)) <= ((n)*get_epsilon<T>()), actual: 1 vs 2.22045e-16
[  FAILED  ] checkin_lapack/BDSVDX.__double/139, where GetParam() = (L, { 1, 2, 1 }, { 1, 5, 15, 0, 0 }) (9 ms)
[ RUN      ] checkin_lapack/BDSVDX.__double/140
C:/workspace/clients/include\testing_bdsvdx.hpp(225): error: Expected equality of these values:
hNsv[0][0]
Which is: 1
hNsvRes[0][0]
Which is: 0
C:/workspace/clients/include\testing_bdsvdx.hpp(528): error: Expected: ((max_error)) <= ((n)*get_epsilon<T>()), actual: 1 vs 2.22045e-16
[  FAILED  ] checkin_lapack/BDSVDX.__double/140, where GetParam() = (L, { 1, 2, 1 }, { 1, 0, 15, 0, 0 }) (8 ms)
[ RUN      ] checkin_lapack/BDSVDX.__double/141
C:/workspace/clients/include\testing_bdsvdx.hpp(225): error: Expected equality of these values:
hNsv[0][0]
Which is: 0
hNsvRes[0][0]
Which is: 1
C:/workspace/clients/include\testing_bdsvdx.hpp(528): error: Expected: ((max_error)) <= ((n)*get_epsilon<T>()), actual: 2 vs 2.22045e-16
[  FAILED  ] checkin_lapack/BDSVDX.__double/141, where GetParam() = (L, { 1, 2, 1 }, { 1, 15, 20, 0, 0 }) (8 ms)
```

2023-02-01 17:47 UTC, jzuniga-amd approved these changes
LGTM. Nice job.

2023-02-01 17:47 UTC, jzuniga-amd commented on clients/include/testing_gesvdx.hpp
> +        EXPECT_EQ(hNsv[b][0], hNsvRes[b][0]) << "where b = " << b;
The code is commented until we sort out the problem with reference lapack, but if you add the assertions for `ifail` and `info` as well, that would be fine.

2023-02-07 19:16 UTC, cgmb commented
@tfalders, @qjojo: could you please review these changes?

2023-02-07 21:12 UTC, tfalders requested changes
Looks good! Just one minor change is needed.

2023-02-07 21:12 UTC, tfalders commented on clients/include/testing_stein.hpp
>                  err++;
Here, we're expecting `hIfailRes[0][j]` to be non-zero. It should be `EXPECT_NE`.

2023-02-07 21:23 UTC, tfalders approved these changes
LGTM. Thanks for adding this!

2023-02-07 21:28 UTC, cgmb commented on clients/include/testing_stein.hpp
>                  err++;
Thanks. I missed that these checks were backwards. It does concern me a little that the tests were still passing. That implies that this code isn't executed. In any case, I've fixed the hIfail checks.

2023-02-07 21:39 UTC, tfalders commented on clients/include/testing_stein.hpp
>                  err++;
This code is only executed if the algorithm doesn't converge, which is a harder situation to create than introducing a singularity into a matrix. I don't think any of our tests right now try to force an algorithm to not converge.

2023-02-08 00:08 UTC, merged