Standardize rocSOLVER documentation builds to use the rocm-docs-core template
ROCmSoftwarePlatform/rocSOLVER pull request #528
Opened 2023-03-10 20:22 UTC by samjwu

JIRA: https://ontrack-internal.amd.com/browse/SWDEV-376988

Summary of proposed changes:
- Updates the readthedocs documentation to use the rocm-docs-core template

Rationale:
- https://github.com/RadeonOpenCompute/rocm-docs-core#purpose

Passing build: https://readthedocs.com/projects/advanced-micro-devices-rocsolver/builds/1344114/

2023-03-10 20:32 UTC, saadrahim commented
Closed and reopened to enable ReadTheDocs business builds.

2023-03-14 21:13 UTC, saadrahim approved these changes

2023-03-15 17:01 UTC, qjojo approved these changes

2023-03-15 18:33 UTC, cgmb requested changes
It mostly looks pretty good, but there are a few broken components, like https://rocsolver--528.org.readthedocs.build/en/528/attributions.html

2023-03-15 20:32 UTC, samjwu commented on docs/attributions.rst
> +.. mdinclude:: ../LICENSE.md
Thanks for the clarification. 
I ended up removing this entirely since @saadrahim wants to have rocm-docs-core generate the sections for legal disclaimers.
But if this is different, I can add it back. Thoughts?

2023-03-15 21:53 UTC, saadrahim commented on docs/attributions.rst
> +.. mdinclude:: ../LICENSE.md
Displaying of rocSOLVER license in the documentation is not needed. All licenses governing ROCm are handled from a central page.

2023-03-17 02:42 UTC, saadrahim commented
MVP needs to be completed. If there are any remaining concerns, please raise them by end of business day Friday.

2023-03-17 17:30 UTC, cgmb commented
I have a few fixes to make. I'll push my changes this afternoon.

2023-03-17 23:40 UTC, cgmb approved these changes
This is a big change. Some things are better and some things are worse when you're looking specifically at rocsolver. However, having this standardized will be a dramatic improvement overall for the ROCm documentation as a whole.

2023-03-18 02:29 UTC, merged