Rocblas interfaces improvements 2
ROCmSoftwarePlatform/rocSOLVER pull request #532
Opened 2023-03-14 18:05 UTC by daineAMD

See rocBLAS changes in [rocblas-internal PR #1698](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1698). This only changes interfaces which include a block size from rocBLAS. It would be good to standardize the entire interface but these PRs are already quite large.

Would like some input regarding the use of ROCBLAS_DOT_NB, I'm guessing this is related to memory allocation needed for rocblas_dot? Can we provide an interface for this, and if so what would you like it to look like?

2023-03-15 16:00 UTC, tfalders requested changes
Thanks for taking care of this, @daineAMD!

There are a number of functions calls that need to be changed. Unfortunately, it looks like `BATCHED` template parameters will need to be added to many different functions.

2023-03-15 20:09 UTC, tfalders commented on library/src/include/rocblas.hpp
> +                               T* y,
The functions that are marked with an overload comment are usually dealing with mixed formats; taking in both batched and strided batched arrays. The last parameter (usually called `workArr`) is required in those cases, so that we can convert the strided batched arrays to batched format. The `get_array` kernel loads pointers to the strided batched matrices into `workArr`, and we call the batched version of the function.

2023-03-15 20:12 UTC, tfalders commented on library/src/include/rocblas.hpp
> +                               T* y,
So dot isn't divided according to batched vs non-batched, it's batched+non-batched vs mixed format.

2023-03-15 22:01 UTC, daineAMD commented on library/src/auxiliary/rocauxiliary_labrd.hpp
>                                      shiftY + idx2D(j + 1, j, ldy), 1, strideY, batch_count);
I've added the BATCHED template parameter where needed. It turned out to be a lot of changes, let me know what you think. The changes seem fine imo, but they could be mostly avoided if I went with overloaded functions in rocblas.hpp for batched/non-batched, rather than using a template parameter. Haven't ran tests locally yet.

2023-03-15 22:04 UTC, daineAMD commented on library/src/include/rocblas.hpp
> +                               T* y,
I've left dot as-is for now, I don't mind being explicit like this since there is the unusual combined batched/non-batched combination, but someone can always simplify it later if desired. Let me know what you think.

2023-03-15 22:21 UTC, TorreZuk commented on library/src/include/rocblas.hpp
>  }
Where the solver side is not batch templated making two templated APIs rocblasCall_scal and rocbalsCall_scal_batched might be simpler.

2023-03-15 22:33 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_labrd.hpp
>                                      shiftY + idx2D(j + 1, j, ldy), 1, strideY, batch_count);
Hmmm, that's a good point, and will probably be cleaner overall.
I feel bad for changing my mind after you already went through the effort of adding the `BATCHED` parameter, but with the new rocBLAS interface it makes a lot more sense to overload the functions as you and @TorreZuk suggested.

2023-03-15 22:46 UTC, daineAMD commented on library/src/auxiliary/rocauxiliary_labrd.hpp
>                                      shiftY + idx2D(j + 1, j, ldy), 1, strideY, batch_count);
I'm ok with either solution. Adding the `BATCHED` template parameters has the upside of potentially making future changes easy, i.e. adding a batched version of an existing function would be much simpler, and makes calls to rocblas explicit. The downside is the code overhead, as seen in my latest commit.

Having two rocblasCall_scal() functions, one accepting batched params, the other accepting non-batched/strided_batched params, has the upside of not needing all of the `BATCHED` template parameters, i.e. less code changes. I'm not sure of the future of rocSOLVER functionality, but the downside would be that these `BATCHED` template parameters could be needed later down the road anyway.

Like I said, I'm ok with either option. I'll leave this for now and maybe we can make a final decision tomorrow after some thought.

2023-03-16 20:10 UTC, daineAMD commented
Updated PR based on discussions, minimal changes to rocSOLVER outside of rocblas.hpp. Let me know if this is what you had in mind/what you think. Running tests locally now.

2023-03-16 21:03 UTC, TorreZuk reviewed
I like it better but not for me to judge.  just the two commented out RCOBLAS_ENTER of note..   I don't know how that system works.  I used ltrace but assume that gives something better.    trsm you simplified a lot do they need to compare performance?

2023-03-16 21:03 UTC, TorreZuk commented on library/src/include/rocblas.hpp
> +    //ROCBLAS_ENTER("axpy", "n:", n, "shiftX:", shiftx, "incx:", incx, "shiftY:", shifty, "incy:", incy, "bc:", batch_count);
uncomment the rocblas_enter I think, but @tfalders can advise if this is not required to debug

2023-03-16 22:09 UTC, tfalders commented on library/src/include/rocblas.hpp
> +    //ROCBLAS_ENTER("axpy", "n:", n, "shiftX:", shiftx, "incx:", incx, "shiftY:", shifty, "incy:", incy, "bc:", batch_count);
Huh. Apparently it's been commented out for a long time, though I'm not sure why. Uncommenting it would be helpful, since it's used for logging.

2023-03-16 22:38 UTC, daineAMD commented on library/src/include/rocblas.hpp
> +    //ROCBLAS_ENTER("axpy", "n:", n, "shiftX:", shiftx, "incx:", incx, "shiftY:", shifty, "incy:", incy, "bc:", batch_count);
Done.

2023-03-16 22:40 UTC, tfalders approved these changes
LGTM!

2023-03-16 22:40 UTC, tfalders commented on library/src/include/rocblas.hpp
>      // nullptr for optional alpha
This comment and the one for batched can probably be removed.

2023-03-17 00:20 UTC, cgmb approved these changes
This is a nice step forward for interface stability between the two libraries.

2023-03-17 03:13 UTC, daineAMD commented
I had a single rocsolver test when testing on my local gfx906, does this look familiar at all? Failed once, but not reproducable:
`[  FAILED  ] checkin_lapack/LASYF.__double/39, where GetParam() = ({ 70, 100, 1 }, { 25, 1 })`

2023-03-17 22:34 UTC, daineAMD commented
rocBLAS PR has been merged. Will check periodically over the weekend on CI for this one once rocblas passes on develop.

2023-03-17 23:14 UTC, cgmb commented
I've enabled automerge, so it will be merged once the CI passes. The commit messages are a bit messy, so I edited it to:
```
Update rocSOLVER to use the more stable rocBLAS internal interfaces
introduced in 9db8ce2db917e97dd62f7f5773369711471702d2. This update
only changes interfaces which include a block size from rocBLAS. It
would be good to standardize the entire interface but these PRs are 
already quite large.

One notable limitation of this change is that the ROCBLAS_DOT_NB
property is hardcoded. Ideally, it would be provided dynamically
through a rocBLAS API.

* Changing rocblas interface to use overloads.

* Adding logging back for axpy.

* Fixing a conjugate dot.
```
Feel free to change it however you desire.

2023-03-18 20:38 UTC, merged