[SWDEV-404616] Updated Copyright Headers
ROCmSoftwarePlatform/rocSOLVER pull request #571
Opened 2023-06-28 17:29 UTC by jibrealkhan

Description: Updated the copyright notice by adding "All rights reserved" and add the BSD-2 license to all files.

2023-07-06 15:04 UTC, jzuniga-amd reviewed
Shouldn't we include the new text in all the files?
For example in `library/scr/lapack/roclapack_gebd2.hpp` after line 7, etc...

2023-07-07 19:11 UTC, qjojo approved these changes

2023-07-07 21:51 UTC, tfalders commented on clients/common/testing_csrrf_analysis.cpp
> + * Copyright (C) 2022-2023 Advanced Micro Devices, Inc. All rights reserved.
Minor issue, but the dates on these csrrf files seem to have been changed.

2023-07-18 22:49 UTC, cgmb requested changes
Sorry for taking so long to review this.

Please note that you also need to update the template in `scripts/reformat-files`.

If you want to see what I see when I review a library's copyright statements, install scan-copyrights with `sudo apt install cme libconfig-model-dpkg-perl` and then run `scan-copyrights` from the root directory of the project.

2023-07-18 22:49 UTC, cgmb commented on CMakeLists.txt
>  # ########################################################################
There's a few issues here. In order from most important to least important:

1. Clause (1) states that `Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.` but no disclaimer follows. You've left out an important part of the license.
2. The lack of whitespace in and around the numbered clauses make them difficult to read.
3. It bugs me when the comment blocks at the top and bottom are too small for the containing text. One thing that would help would be to continue using just a single space after the `#`.

To address these issues for shell, Python and CMake files, I suggest using this template:
https://github.com/cgmb/rocSOLVER/blob/6fda8116bafbe67fe05ee0cceb92709737d244cb/CMakeLists.txt#L1-L26

For C and C++ files, I suggest using this template:
https://github.com/cgmb/rocSOLVER/blob/6fda8116bafbe67fe05ee0cceb92709737d244cb/library/include/rocsolver/rocsolver.h#L1-L26

I've opened https://github.com/jibrealkhan/rocSOLVER/pull/1 with these suggested templates. Since you've been quite consistent in these headers, it should be pretty straight-forward to write a simple find-and-replace script to apply this change (or one like it) to update to all files.

2023-07-18 22:49 UTC, cgmb commented on library/include/rocsolver/rocsolver.h
> + * Copyright (C) 2019-2023 Advanced Micro Devices, Inc. All right reserved.
This should be `All right reserved.`

2023-07-18 22:54 UTC, cgmb commented on clients/common/testing_csrrf_analysis.cpp
> + * Copyright (C) 2022-2023 Advanced Micro Devices, Inc. All rights reserved.
In general, I don't think any existing copyright dates should be changed by this update. The guidelines are that we should update the date whenever we make a substantial modification and a change to the copyright block itself probably doesn't count. That said, it's not a big deal either way.

2023-07-18 23:09 UTC, cgmb commented
With regards to the JIRA ticket number, I would put it at the end rather than at the beginning. There are two reasons for that:

1. rocSOLVER is an open-source project and most development is done in public. However, that number refers to a bug tracker that most users and external contributors do not have access to. It doesn't deserve such a prominent position when it's only useful to some people.
2. If it's in the body text of the PR, it will be automatically turned into a hyperlink. For people who have access to our bug tracker, it's actually more convenient to have it in the extended description.

So, I would suggest just putting it at the end of your PR description, like:

Ticket: SWDEV-404616

2023-08-31 14:19 UTC, closed without merging