splitLU optimization
ROCmSoftwarePlatform/rocSOLVER pull request #631
Opened 2023-11-14 17:08 UTC by EdDAzevedo

New code to improve the performance of rocsolver_dcsrrf_splitlu() by using the header-only rocthrust library to compute in-place inclusive prefix scan sum.
(SWDEV-431135)

2024-01-05 20:06 UTC, tfalders requested changes
Here are some preliminary comments. I haven't fully reviewed the kernel code yet because I would like have some concerns about the indexing scheme. Once we've settled those concerns, I'll continue my review.

2024-01-05 20:06 UTC, tfalders commented on CMakeLists.txt
> +find_package(rocprim REQUIRED CONFIG PATHS ${ROCM_PATH})
Since this is currently only required by splitlu, I'd suggest only requiring rocPRIM when BUILD_WITH_SPARSE is true. It's probably also a good idea to specify a minimum version. Perhaps @cgmb can advise.

2024-01-05 20:06 UTC, tfalders commented on library/src/CMakeLists.txt
> +    roc::rocprim
If we only require rocPRIM when we BUILD_WITH_SPARSE, then this will need to be moved down into the BUILD_WITH_SPARSE section.

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +#undef HIP_CHECK
This can be removed

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    assert(istat == hipSuccess);
assert only works in the debug build. I would instead suggest returning a status code, which the _impl method will need to check.

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                                           rocblas_int* LUp,
For consistency, please rename to ptrT.

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    if(use_alg1)
This is the kind of situation where we would add a named constant to ideal_sizes.hpp and use that instead of 64, e.g. n <= SPLITLU_SWITCH_SIZE. use_alg1 is also unnecessary and can be moved directly into the if statement.

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        rocblas_int* const Up = ptrU;
This is unnecessary. Please use ptrL and ptrU directly.

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +            storage_size_bytes = size_work;
This looks like it belongs in getMemorySize, rather than the template method

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        }
I would suggest using our reset_batch_info kernel in lib_device_helpers.hpp to do this instead of hipMemcpyAsync. Reason being that reset_batch_info can work with batched and strided batched arrays, and we might want to add batched versions of splitlu at some point.

Although, this opens up a question: Does rocPRIM have batch functionality?

2024-01-05 20:06 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    for(auto irow = wid; irow < n; irow += nwaves)
I don't understand what you're trying to accomplish here. What exactly is waveSize supposed to represent? Wouldn't it make more sense to launch a 2D kernel directly rather than convert indices within a 1D kernel?

Plus, I'm pretty sure our test data never meets the conditions in cal_wave_size, meaning waveSize is always 1 and we aren't testing whether this code works properly.

2024-01-08 10:44 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +#undef HIP_CHECK
#undef HIP_CHECK is removed

2024-01-08 10:53 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    assert(istat == hipSuccess);
rocsolver_csrrf_splitlu_getMemorySize returns a rocblas_status as well

2024-01-08 10:56 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                                           rocblas_int* LUp,
renamed LUp to ptrT

2024-01-08 11:08 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    if(use_alg1)
added SPLITLU_SWITCH_SIZE in ideal_sizes.hpp

2024-01-08 11:26 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        rocblas_int* const Up = ptrU;
I think using intermediate variables as const expression should have no or insignificant impact on code quality. The compiler can (should) inline the const expression if the compiler chooses.

I think the use of intermediate variables is for the benefit of the developer.   For example,  it may be necessary to be compatible with cuda library to use say function argument variables as csrRowPtrA, csrColIndA, csrValA but the convention with another library, say,  SuiteSparse uses Ap, Ai, Ax for conceptually the similar arrays. So it may be convenient for one developer to use intermediate variables  as something like   "auto const Ap =csrRowPtrA;" when working with  SuiteSparse Library or in writing more compact code.     

Conversely,  a developer not familiar with the naming convention of SuiteSparse might prefer a more meaningful variable name and prefer to use  "auto const csrRowPtrA = Ap;" instead.

I see no harm in using intermediate variables for the benefit of the developer.

2024-01-08 11:27 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +            storage_size_bytes = size_work;
This is extra check for robustness.

2024-01-08 11:35 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        }
I think at some point if we wish to add batch capability, then all  relevant code (and code interface) should be modified to have batch capability. A mixed hybrid code with partially implemented batch capability might not be the best approach.  Rocsolver will also need to wait for batch capability in rocsparse.

If the batch interface assumes all sparse matrices in the batch list have the same sparsity pattern but may have different numerical values, then we do not need batch capability in rocPRIM.

2024-01-08 11:53 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    for(auto irow = wid; irow < n; irow += nwaves)
The performance of sparse matrix algorithms is commonly related to data access and not limited by flops. Ideally, we would like to have stride-1 coaslesced access to the arrays in compressed sparse row format. Thus one may wish to assign at least a  full warp to process one row. However, if the average number of non-zeros per row is small say about 15 nonzeros, then using all 64 threads in a warp may not be efficient since most of the threads will have no work. One may consider assigning say 8 threads to process one row and process 8 rows concurrently by the warp.  I use a conceptual virtual "wave" of threads to process one row. 

In using a 2D array of threads in a block, a programmer dealing with Fortran data structure might want threads in the conceptual "x" dimension to be contigous threads in the same warp to have coaslesced data access. Similarly, a programmer dealing with C array data structure might want threads in the conceptual "y" dimension to be contiguous threads in the same warp.  By using a 1D decomposition, there is no ambiguity and clearly that all threads  in a conceptual virtual "wave" are contiguous threads in the same warp.  There is also more flexibility in decoupling of the launch configuration and kernel code. By using a 1D decomposition, the kernel code will still work correctly independent of the launch configuration.

If the test data never meets the conditions in cal_wave_size() that the average number of non-zeros per row in our test matrices is always a small number, then I think we should add more tests. For example, we might consider storing a fully dense matrix or wide banded matrix in CSR format to test the code (not just splitlu) works properly.

2024-01-08 15:34 UTC, EdDAzevedo commented on CMakeLists.txt
> +find_package(rocprim REQUIRED CONFIG PATHS ${ROCM_PATH})
I'll leave cmake issues to Cory the expert.

2024-01-08 15:35 UTC, EdDAzevedo commented on library/src/CMakeLists.txt
> +    roc::rocprim
I'll leave cmake issues with Cory the expert.

2024-01-08 21:01 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    for(auto irow = wid; irow < n; irow += nwaves)
The main advantage of using a 2D kernel in this case would be that you'd only have to do these computations once, rather than in each kernel. This would also reduce code redundancy, which could also be accomplished by moving some of the code into cal_wave_size.

There's an additional possibility that the kernel could be launched with nthreads not evenly divisible by waveSize, e.g. if a user altered the value of BS1. I believe this would cause some elements to be missed by the kernel. This shouldn't happen with an explicitly 2D kernel.

It would be good to have the explanation for what a wave is included as comments in the code.

2024-01-09 04:27 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    for(auto irow = wid; irow < n; irow += nwaves)
The number of threads assigned to process each row is based on a heuristic related to the average number of nonzeros per row and this number of nonzeros is assumed to be computed by the ptrT array on GPU. Thus one would need to copy this value back to host to set the 2D launch configuration.  I'll add more comments about the conceptual virtual "wave" of threads assigned to process each row in the routine cal_wave_size(). 

I don't think whether 1D or 2D will make a big difference since a significant amount of  the time is spent in the rocPRIM for computing prefix sum. 

The code assumes warpSize is a power of 2 and the number of threads per thread block is also a multiple of warpSize. I'll add an assertion to check this so that the correctness of the code can be checked during internal rocsolver test. I'll add  SPLITLU_BS1 variable  so that it will be a multiple of warpSize.

It would be interesting to see if  BS1 is modified to say BS1=127, or BS2 = 13, whether the rocsolver library will still work correctly.

2024-01-17 23:25 UTC, cgmb commented on CMakeLists.txt
> +find_package(rocprim REQUIRED CONFIG PATHS ${ROCM_PATH})
Sounds good to me.

2024-02-03 01:01 UTC, tfalders reviewed
I have just some minor comments on the remainder of the code. There is one comment from my previous review that I'd like to reopen, but other than that I think it's almost ready.

2024-02-03 01:01 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                nzLarray[irow] += 1; // add 1 for unit diagonal
This is two writes to global memory. It'll be faster if you combine them, i.e. `nzLarray[irow] = (kdiag - kstart)`

2024-02-03 01:01 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    rocblas_int* const diagpos = work;
You may wish to consider using shared memory instead of global memory for this. That should make it a little faster.

2024-02-03 01:05 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +            storage_size_bytes = size_work;
I'd still like to see this moved to getMemorySize. Reason being that it doesn't make sense for the function to fail when the cause of the failure can be easily addressed on our side. If size_work is taken to be `max({rocprim_size_bytes, storage_size_bytes_Lp, storage_size_bytes_Up, size_work_LU})`, then we can ensure that `size_work >= storage_size_bytes` and therefore this check is no longer needed and the function won't fail.

2024-02-03 21:50 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                nzLarray[irow] += 1; // add 1 for unit diagonal
I'll add 1 in line 116.

2024-02-03 22:07 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    rocblas_int* const diagpos = work;
Added code to check whether the array required can fit in LDS shared memory, otherwise use global memory.

2024-02-03 22:16 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +            storage_size_bytes = size_work;
the code to check storage for rocprim is removed

2024-02-06 22:57 UTC, tfalders approved these changes
A couple more minor comments, but it's in a state now where I feel comfortable approving.

2024-02-06 22:57 UTC, tfalders commented on library/src/include/ideal_sizes.hpp
> +#define SPLITLU_BS1 256
Now that the kernel has been made 2D, I think this can be removed and BS1 can be used instead

2024-02-06 22:57 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.cpp
> +    }
You can simplify this code by using the ROCBLAS_CHECK macro, i.e. `ROCBLAS_CHECK(rocsolver_csrrf_splitlu_getMemorySize<T>(n, nnzT, ptrT, &size_work));`

2024-02-06 22:57 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        wid = hipThreadIdx_y + hipBlockIdx_x * hipBlockDim_y; \
I'm confused why it's hipBlockDim_y you're using here instead of hipBlockDim_x. How does this work?

2024-02-06 22:57 UTC, tfalders commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    }
You can simplify this using the HIP_CHECK macro

2024-02-07 00:00 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        wid = hipThreadIdx_y + hipBlockIdx_x * hipBlockDim_y; \
The launch configuration is dim3(nblocks,1,1), dim3(nx,ny,1),   where nx is the number of threads in a conceptual "wave",  and there are ny waves per thread block. 

Thus there are a total of (nblocks * ny ) waves.  The "wid"  identification number of the wave is   threadIdx_y +   blockIdx_x * ny,   where ny is BlockDim_y.

2024-02-07 00:02 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.cpp
> +    }
I have changed the code to use ROCBLAS_CHECK macro.

2024-02-07 00:05 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    }
I have changed the code to use HIP_CHECK macro.

2024-02-23 04:42 UTC, EdDAzevedo commented on library/src/include/ideal_sizes.hpp
> +#define SPLITLU_BS1 256
SPLITLU_BS1 is removed from ideal_sizes.hpp,  refact/rocrefact_csrrf_splitlu.hpp modified to use BS1

2024-03-20 18:19 UTC, cgmb reviewed
I had a few minor comments. The most important is related to the printf, as that has user-visible impact. The rest are merely small suggestions.

2024-03-20 18:19 UTC, cgmb commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +#define SETUP_THREADS(lid, wid, waveSize, nwaves)             \
Could we perhaps call this `SPLITLU_SETUP_THREADS` to reflect that it is specific to this function?

2024-03-20 18:19 UTC, cgmb commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                       irow, nnzTrow, nnzLrow, nzLarray[irow], nnzUrow, nzUarray[irow]);
I think this printf should probably be guarded behind `#ifndef NDEBUG` so it's only in debug builds. However, if you really want to keep it in release builds distributed to end users, it needs to have a message that can be understood by those users.

2024-03-20 18:19 UTC, cgmb commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        for(auto irow = 0 * n; irow < n; irow++)
`auto irow = 0 * n;` is a rather awkward construction. I realize that the multiplication will be optimized away, but this is really just `rocblas_int irow = 0;`. I think that would be more clear. If you really want to use type deduction for the index, I would go with `using index_type = decltype(n); index_type irow = 0;`.

2024-03-20 18:19 UTC, cgmb commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    return (rocblas_status_success);
It's not a big deal, but ideally all team members would write code in a similar enough style to be indistinguishable. The parentheses around return values are unnecessary and don't match the rest of the project, so I'd recommend omitting them.

That said, these have no actual impact on the end result and I don't think it will make the code any less clear for other contributors. This is just a nitpick.

2024-03-20 20:08 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +    return (rocblas_status_success);
I'll use the form "return i + j * ld  " instead of "return( i + j * ld )"

2024-03-20 20:11 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +        for(auto irow = 0 * n; irow < n; irow++)
I'll declare the type to use "for( rocblas_int irow = 0".

2024-03-20 20:11 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +                       irow, nnzTrow, nnzLrow, nzLarray[irow], nnzUrow, nzUarray[irow]);
I'll guard this using "NDEBUG".

2024-03-20 20:14 UTC, EdDAzevedo commented on library/src/refact/rocrefact_csrrf_splitlu.hpp
> +#define SETUP_THREADS(lid, wid, waveSize, nwaves)             \
I'll change this to SPLITLU_SETUP_THREADS.

2024-03-21 19:20 UTC, cgmb approved these changes

2024-03-21 19:24 UTC, cgmb commented
There was a logical conflict in the changes to the CI configuration needed for this PR and #677. It added getRocPRIM only for the static case, but this PR needs it for the dynamic library build as well. You'll need to back out the `getRocPRIM`-related changes from #677 in `.jenkins/common.groovy` to resolve the conflict.

2024-04-08 17:37 UTC, jzuniga-amd approved these changes
LGTM. 
Probably better to merge #689 first.

2024-04-15 20:59 UTC, tfalders commented
There were some new files added: TAGS, testing_csrrf_splitlu.hpp.dev, and testing_csrrf_splitlu.hpp.org. Are these necessary, or can they be removed?

2024-04-15 21:20 UTC, tfalders commented
I'll do the merge once the tests pass again. I'll merge my getf2 PR first. I don't expect any merge conflicts, so you should be fine to leave this PR as it is.

2024-04-15 23:52 UTC, merged