changelog & readme updates
ROCmSoftwarePlatform/rocSOLVER pull request #635
Opened 2023-11-24 19:19 UTC by LisaDelaney

2023-11-29 23:01 UTC, saadrahim approved these changes

2023-11-29 23:01 UTC, saadrahim commented
@tfalders @cgmb @jzuniga-amd @qjojo Can you please review this change?

2023-11-30 05:38 UTC, jzuniga-amd commented on CHANGELOG.md
> -### Security
Please do not remove the Unreleased lines above. Change them for Additions, Optimizations, Changes, etc.. 
We populate the changelog as we commit to `develop` during the development cycle (for 6.2 in this case).

2023-12-01 15:52 UTC, LisaDelaney commented on CHANGELOG.md
> -### Security
I've added "(unreleased)" to the appropriate headings. Can we just add the relevant sub-headings when we have content for them?

2023-12-07 20:51 UTC, cgmb commented on CHANGELOG.md
> -### Security
The empty headings are used to prevent merge conflicts when developers add new entries to the changelog. Unfortunately, our current process of updating CHANGELOG.md in every PR creates a lot of merge conflicts since almost every PR needs to change the same part of the same file.

I've been advocating to replace that with a process that generates the changelog update from `Changelog:` notes in the git commits going into the release. An automated job would open a PR to update CHANGELOG.md at feature complete.

2024-02-09 23:18 UTC, Rmalavally commented on CHANGELOG.md
> +### Known Issues
@LisaDelaney Do you want to remove known issues and security?

2024-02-09 23:33 UTC, LisaDelaney commented
@jzuniga-amd how does this version look?

2024-02-13 00:23 UTC, tfalders requested changes
Apologies for putting this off for so long. Here are my comments and the changes I would like to see. The comment about the newline spacing also applies to the hipSOLVER PR, which I intend to review soon.

2024-02-13 00:23 UTC, tfalders commented on CHANGELOG.md
> +## (unreleased) rocSOLVER 3.25.0 for ROCm 6.1.0
I don't agree with putting `unreleased` on previous dev cycles that are pending release. This will just be one more thing for us to have to keep track of and remove when it's time. At the very least, `unreleased` should be capitalized.

2024-02-13 00:23 UTC, tfalders commented on CHANGELOG.md
> +  * HEGVDJ (with `batched` and `strided_batched` versions)
This has been added to the Changed section when it belongs in the Added section. Plus, the newline spacing is inconsistent with other sections.

2024-02-13 00:23 UTC, tfalders commented on CHANGELOG.md
> +* Added `rocsolver_rfinfo_mode` and the ability to specify the desired refactorization routine (see `rocsolver_set_rfinfo_mode`)
I don't agree with the newline spacing in this PR. It makes it more difficult to separate different releases in raw view. Please either revert to the original spacing, or more clearly demarcate the different releases.

2024-02-13 00:23 UTC, tfalders commented on CHANGELOG.md
> +* Returned values in the parameter information of functions dealing with singularities
I believe the original line referred to an actual function parameter named `info`. Please restore the name to `info`.

2024-02-13 00:23 UTC, tfalders commented on README.md
> +If you're a developer contributing to rocSOLVER, you can run `./scripts/install-hooks` to install the githooks for autoformatting. Before contributing, refer to our
Minor comment, but I feel like "you're" is too informal for our documentation; "you are" would be preferred.

2024-02-20 21:20 UTC, LisaDelaney commented on README.md
> +If you're a developer contributing to rocSOLVER, you can run `./scripts/install-hooks` to install the githooks for autoformatting. Before contributing, refer to our
I'm trying to make our documentation more approachable and conversational, so I'm transitioning to contractions throughout.

2024-04-16 04:20 UTC, closed without merging