Fix refactchol
ROCmSoftwarePlatform/rocSOLVER pull request #637
Opened 2023-11-28 01:56 UTC by EdDAzevedo

Remove argument "beta" from  rf_add_QAQ_kernel and use hipMemsetAsync() to set array "valT" to zero.

2023-11-28 18:47 UTC, tfalders requested changes
Nice job! Thanks again for finding the cause of the bug.

I've opened a PR on your local fork to adjust the code style for consistency. Please look it over when you have some time.

2023-11-28 18:47 UTC, tfalders commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
As I have been recently reminded, assert only works in the debug build. We'll probably have to add a rocblas_status to these TRSM methods and return an internal error if the status is not a success, which is a bit beyond the scope of this PR. I'd recommend moving the changes to this file into a new PR where we can iron out what needs to be done.

2023-11-28 18:52 UTC, jzuniga-amd commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
In fact, the workaround in TRSM should not be needed anymore (with the new hardware/firmware stack). So all this code could be removed completely. I am running the entire test suite on the node to confirm this is the case.

2023-11-28 20:05 UTC, EdDAzevedo commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
Perhaps there should be a consistent standard HIP_CHECK() macro in a standard header file  for all  of the rocsolver source code?

2023-11-28 20:28 UTC, jzuniga-amd commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
I ran the entire rocsolver test suite without this TRSM workaround and everything is passing. This code was only temporal and is not needed anymore. It can be safely removed.

2023-11-28 21:35 UTC, tfalders commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
Even on 940?

2023-11-29 00:11 UTC, jzuniga-amd commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
right!! 940 and 941 should stay in the condition.

2023-11-29 18:54 UTC, tfalders commented on library/src/specialized/roclapack_trsm_specialized_kernels.hpp
> +#endif
I have opened a new PR against @EdDAzevedo's fork to address these issues. Please have a look when you're able.

2023-11-29 19:01 UTC, tfalders approved these changes

2023-11-29 19:10 UTC, jzuniga-amd approved these changes
LGTM

2023-11-30 21:24 UTC, merged