Improve performance of sorting eigenvalues and eigenvectors using shell sort
ROCmSoftwarePlatform/rocSOLVER pull request #651
Opened 2024-01-12 01:48 UTC by EdDAzevedo

Improve performance of sorting eigenvalues and eigenvectors in "stedc_sort"  kernel using shell sort (instead of selection sort).  The shell sort algorithm is described on wikipedia. 

The shell sort algorithm works on a single thread block so that all threads can be synchronized using __syncthreads().  A single thread is first used to sort the eigenvalues and to generate the permutation vector.   Then repeated swap operations on columns of "C" matrix  containing eigenvector (using all threads in the thread block)  are used to implement the action of permutation vector. 

Note  integer temporary storage of length (n) (for each thread block) will be needed to hold the permutation vector.

2024-01-26 19:47 UTC, tfalders requested changes
Looks pretty good, though I have a number of comments to be addressed.

2024-01-26 19:47 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_bdsvdx.hpp
> +                                strideF, info, map_array);
This is an unacceptable way to declare map_array. A better (and easier) way to do it is to pick a single workspace array that will be reused for map_array, ideally one that already has enough space such as isplit or iblock, and stick with it.

To help with readability, the name of the workspace array you pick should be changed, e.g. to isplit_map or iblock_map, across the entire file. Changing it in the associated cpp files is recommended but not strictly necessary. Changing it also in functions that call bdsvdx is a nice-to-have, but I won't complain if it's not done.

2024-01-26 19:47 UTC, tfalders commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +        rocblas_int* map_array = nullptr;
Same comment as for bdsvdx. Both iblock and isplit are good candidates to reuse for map_array.

2024-01-26 19:47 UTC, tfalders commented on library/src/lapack/roclapack_syevdx_heevdx_inplace.hpp
> +        rocblas_int* map_array = nullptr;
Same comment as for bdsvdx. Both iblock and isplit are good candidates to reuse for map_array.

2024-01-26 19:47 UTC, tfalders commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +    ;
This semicolon can be removed

2024-01-26 19:47 UTC, tfalders commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +        __syncthreads();
Assert only works in the debug build. In the release build, this loop will waste time doing nothing. It should either be placed in a preprocessor macro or removed (or changed to do something in release mode but I'm not sure how to go about that).

2024-01-26 19:47 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +                                    D + shiftD, strideD, C, shiftC, ldc, strideC, batch_count, work);
If I'm reading this correctly, this kernel is always going to be launched with 64000 blocks, which is way too many in the vast majority of cases. I know we've talked about the possibility of batch_count exceeding the maximum number of thread blocks, but this is not a suitable remedy. I would prefer that we stuck with launching batch_count blocks, at least until we've devised a suitable pattern that can be used across the library.

2024-01-26 19:47 UTC, tfalders commented on library/src/include/lib_device_helpers.hpp
> +    // ------------------------
I'm not sure if deriving code from Wikipedia is okay for us to do or not, and to what extent (if any) we need to differentiate our code from theirs.
It also looks like the comments are verbatim the same as on Wikipedia, which will probably need to be removed or rephrased.
Perhaps @doctorcolinsmith can advise?

2024-01-26 19:47 UTC, tfalders commented on library/src/include/lib_device_helpers.hpp
> +    auto const k_inc = (hipBlockDim_x * hipBlockDim_y) * hipBlockDim_z;
It's a little strange for me to see the x, y, and z dimensions being referenced even though the function seems to be 1D. I'm guessing it's to allow the function to be used by 1D, 2D, and 3D kernels. Usually we don't use these built-in HIP functions in our device functions; instead we would pass k_start and k_inc as parameters. Not a big deal, but I thought I'd mention it.

2024-01-26 19:47 UTC, tfalders commented on library/src/include/lib_device_helpers.hpp
> +__device__ static void shell_sort_descending(const I n, S* a, I* map = nullptr)
A minor point, but it would be nice to have associated methods grouped together in the file. An example ordering of methods in the file could be:
- shell_sort_ascending
- shell_sort_descending
- shell_sort
- selection_sort_ascending
- selection_sort_descending
- selection_sort
- permute_vector

2024-01-26 21:21 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_bdsvdx.hpp
> +                                strideF, info, map_array);
The original method is robust with defensive programming in the sense that it will always work and does not require detailed knowledge of other parts of implementation. If say work1_iwork[]  has sufficient storage, then it will always use work1_iwork[]. It also tries to use storage arrays named "work" and try not use named arrays, in case those arrays might contain information that needs to be preserved across different kernel launches.   It is also future proof in the sense in case in future  if the code reduces the storage for isplit[] to less than n integers for each batch item,  the original method will still work since it will try to use another temporary array with sufficient storage.  A general name like "map_array" has the advantage that if in future isplit[] has less than n integers and we need to use say iblock[] instead, then we'll need to modify the code to rename isplit_map[] to iblock_map[].  The original method also has insignificant impact to performance. 

Ideally, one can call the stream-oriented pool memory allocator to allocate and deallocate as needed. This can greatly simplify the code and improve robustness and maintainability.
--------------------
I'll modify the code to always use isplit[] and rename map_array[] to isplit_map[].

2024-01-26 21:26 UTC, EdDAzevedo commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +        __syncthreads();
I'll add #ifdef NDEBUG  to perform the extra check only during testing and not in production code.

2024-01-26 21:30 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +                                    D + shiftD, strideD, C, shiftC, ldc, strideC, batch_count, work);
The launch configuration will use the min(  max_blocks, batch_count), so if batch_count is say 47, then it will use only 47 blocks. If the batch_count is say  1,000,000,  it will use only max_blocks of 64000 thread blocks. Internally the kernel will use a loop to process 64000 batch items concurrently in each iteration.

2024-01-26 21:36 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +    // ------------------------
I'll remove the comments.

2024-01-26 21:41 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +    auto const k_inc = (hipBlockDim_x * hipBlockDim_y) * hipBlockDim_z;
Yes, it is defensive programming for robustness that this library routine will still work even with different launch configuration of 1D, or 2D or 3D grid of threads in a thread block. The kernel may be launched with say a 3D grid of threads in a thread block, but this library routine will still correctly perform the sorting.

2024-01-26 21:49 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +__device__ static void shell_sort_descending(const I n, S* a, I* map = nullptr)
The code is rearranged.

2024-01-26 22:01 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +                                    D + shiftD, strideD, C, shiftC, ldc, strideC, batch_count, work);
Another possible advantage in restricting the launch configuration  is if batch_count is large, we need scratch storage that scale as  O( min( batch_count,max_blocks))  and not O( batch_count ) since we know there will be at most O(max_blocks ) active concurrent computations.    

If the machine has only about say 128  Compute Units (CU), then maybe launch configuration of say max_blocks=512  blocks are already sufficient to keep the machine fully occupied. Using a smaller number of max_blocks may reduce the amount of scratch space required to scaling as O(512) instead of O(batch_count).

2024-01-26 22:06 UTC, EdDAzevedo commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +    ;
I have removed that extra semicolon.

2024-01-26 22:16 UTC, EdDAzevedo commented on library/src/lapack/roclapack_syevdx_heevdx_inplace.hpp
> +        rocblas_int* map_array = nullptr;
I'll rename map_array[] to isplit_map[] and assign  isplit[] to isplit_map[].

2024-01-29 18:09 UTC, tfalders commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +                                    D + shiftD, strideD, C, shiftC, ldc, strideC, batch_count, work);
Ah, somehow I missed the min in that call. That makes a lot more sense now.

This does bring up some different comments though, namely:
1. There are other kernels in the function that are not using this pattern. If batch_count exceeds the maximum number of blocks, then they will cause the function to fail before it ever reaches this kernel.
2. 64000 is what we call a "magic number". It would be better if it were defined as a constant in ideal_sizes.hpp, or better yet, queried from the device properties.

Whenever we change a pattern like this, I prefer to do it all at once across the entire library in a separate PR. So, while I still recommend sticking with launching batch_count blocks, this is with the understanding that we will later adopt a pattern similar to this across the entire library.

2024-01-29 18:33 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +                                    D + shiftD, strideD, C, shiftC, ldc, strideC, batch_count, work);
OK. I'll remote max_blocks.  

I think the main advantage is in reducing the amount of scratch space required to scaling as O(max_blocks) instead of scaling as O(batch_count), especially when the value of batch_count is large.  In the case of sorting, we need O(n) temporary storage to hold the permutation vector. By restricting the launch configuration to only max_blocks thread blocks, it can reduce the storage requirement from "n * batch_count" to only "n * max_blocks".

According to this web page, in cuda the y and z grid dimensions have a limit of 65535. So it may be  possible that a hip program using hipsolver library with batch_count larger than this limit may work on AMD gpu but may fail on cuda.

https://en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

2024-01-31 01:14 UTC, tfalders commented
The changes to map_array are an improvement, though not quite what I had in mind. I've opened a PR on your fork with my suggested changes.

2024-01-31 18:48 UTC, tfalders approved these changes
Looks good! A 2nd review will also be needed, and it would nice to have a go-ahead from @doctorcolinsmith, but after that we can squash-and-merge and get this into the library.

2024-01-31 22:24 UTC, doctorcolinsmith commented
@tfalders No concerns from me.

2024-02-05 21:47 UTC, jzuniga-amd reviewed
Just a few very minor comments below

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
>  /** BDSQR_SORT sorts the singular values and vectors by selection sort if applicable. **/
this comment is no longer valid and not in the right place

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
> +    // identity permutation 0,1,2,...
You can add the description of the function right before its declaration as for all the other functions in the file. Just to keep consistency.

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> + * *****************************************/
there is a misplaced end of line here

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> + * *********************************************************/
same here

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +        auto const nblocks = max(1, batch_count);
this `max` takes some unnecessary extra time. batch_count cannot be less than 1 at this point (invalid values should be detected with the check_argument helper of the batched functions that may call stedc)

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> + * *****************************************/
extra end line again

2024-02-05 21:47 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> + * ********************************************/
idem

2024-02-06 03:50 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
> +        bdsqr_permute_swap(n, nv, V, ldv, nu, U, ldu, nc, C, ldc, map);
You need to call the `permute_swap` function only `if(nu || nv || nc)`.
You can save some cycles this way because `permute_swap` will still restore map into the identity even if there are no vectors to permutate

2024-02-06 14:28 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
>  /** BDSQR_SORT sorts the singular values and vectors by selection sort if applicable. **/
I have updated the position of the comment and mention shell sort.

2024-02-06 14:30 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> + * *****************************************/
I have joined the two lines. The line split may be due to clang-format trying to reformat code and long comments to be less than 80 columns.

2024-02-06 14:31 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +        auto const nblocks = max(1, batch_count);
I have removed the max.

2024-02-06 14:32 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> + * *****************************************/
I have joined the two lines.

2024-02-06 14:32 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> + * ********************************************/
I have joined the two lines.

2024-02-06 14:38 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
> +        bdsqr_permute_swap(n, nv, V, ldv, nu, U, ldu, nc, C, ldc, map);
add test for "bool const need_swap = (nu > 0) || (nv > 0) || (nc > 0);" before calling permute_swap().

2024-02-06 14:52 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_bdsqr.hpp
> +    // identity permutation 0,1,2,...
I have moved the description of the function to right before its declaration.

2024-02-07 02:02 UTC, jzuniga-amd approved these changes
LGTM. Don't forget to merge Troy's changes to stedcj

2024-02-07 17:40 UTC, cgmb approved these changes
I have only superficial comments.

2024-02-07 17:40 UTC, cgmb commented on library/src/include/lib_device_helpers.hpp
> +#else
`#ifndef`?

2024-02-07 17:40 UTC, cgmb commented on library/src/include/lib_device_helpers.hpp
> +    };
It's not important enough to be worth going back and changing, but in the future please match the style of the surrounding code and omit these semi-colons. The ideal would be for all contributors to have a consistent style.

2024-02-07 17:40 UTC, cgmb commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +    assert(nev <= n);
IMO, this may be good place for `ROCSOLVER_ASSUME_X(condition, message)`. It resolves to `[__builtin_assume`](https://clang.llvm.org/docs/LanguageExtensions.html#builtin-assume) in release builds and `assert` in debug builds.

Although, I think I might have broke the ability to use it in device code. So, maybe this isn't a suggestion for right now, but for next time...

2024-02-07 17:40 UTC, cgmb commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +    }
There's a `ROCSOLVER_UNREACHABLE_X(message)` macro for this. It resolves to ][`__builtin_unreachable`](https://clang.llvm.org/docs/LanguageExtensions.html#builtin-unreachable) in release mode and `assert(false)` in debug mode...

Although, I may broken it in device code by trying to be too clever with displaying the error message... so maybe that's a suggestion for once I fix that.

2024-02-23 04:22 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +#else
I was trying to avoid double negative  "if not defined not debug"

2024-02-23 04:30 UTC, EdDAzevedo commented on library/src/lapack/roclapack_syevx_heevx.hpp
> +    assert(nev <= n);
In the url https://clang.llvm.org/docs/LanguageExtensions.html#builtin-assume, it seems to me "__builtin_assume" is intended for clang compiler optimization and perhaps not intended for the purpose of checking correctness. There is mention "If the condition is violated during execution, the behavior is undefined."

2024-02-23 04:34 UTC, EdDAzevedo commented on library/src/auxiliary/rocauxiliary_stedc.hpp
> +    }
It seems to me "__builtin_unreachable" is intended for clang compiler optimization. It may not be intended for checking for coding error.

2024-02-23 04:35 UTC, EdDAzevedo commented on library/src/include/lib_device_helpers.hpp
> +    };
I have removed the semi-colons.

2024-02-23 18:23 UTC, randyh62 reviewed
Looks good to me.

2024-03-06 18:21 UTC, merged