Added stedcj
ROCmSoftwarePlatform/rocSOLVER pull request #654
Opened 2024-01-17 19:15 UTC by tfalders

Adds stedcj to the internal API

2024-01-18 17:05 UTC, jzuniga-amd requested changes
Looks good. Cleaner and more organized than having all combined in a single file. 
(We can probably re-use some code on the clients side, but we can leave it for later; I want to do a thorough revision of all the clients code anyways).
Just a few minor comments below. 
Also, as we are leaving the test code, please add it to the bench client as well (`rocsolver_dispatcher.hpp`, etc). It would be useful to call `stedcj` from the bench client to do direct comparisons with `stedc` or `stedcx` for example.

2024-01-18 17:05 UTC, jzuniga-amd commented on clients/common/testing_stedcj.cpp
> + * Copyright (C) 2022-2024 Advanced Micro Devices, Inc. All rights reserved.
This is a new file, maybe just put Copyright (C) 2024

2024-01-18 17:05 UTC, jzuniga-amd commented on clients/include/testing_stedcj.hpp
> + * Copyright (C) 2020-2024 Advanced Micro Devices, Inc. All rights reserved.
2024

2024-01-18 17:05 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedc.hpp
>  #define MAXSWEEPS 20 // Max number of sweeps for Jacobi solver (when used)
MAXSWEEPS probably not needed here anymore ?

2024-01-18 17:05 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.cpp
> + * Copyright (C) 2021-2024 Advanced Micro Devices, Inc. All rights reserved.
2024

2024-01-18 17:05 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.cpp
> +    rocblas_status st = rocsolver_stedcj_argCheck(handle, evect, n, D, E, C, ldc, info);
maybe can reuse `stedc_argCheck` ?
signatures are identical

2024-01-18 17:05 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> + * Copyright (C) 2021-2024 Advanced Micro Devices, Inc. All rights reserved.
Year 2024. 
Also maybe we can remove the LAPACK notice. This routine does not exist in LAPACK.

2024-01-18 17:05 UTC, jzuniga-amd commented on library/src/auxiliary/rocauxiliary_stedcj.hpp
> +rocblas_status rocsolver_stedcj_argCheck(rocblas_handle handle,
This helper is the same as in `stedc`. Maybe we can reduce repetition and use just that one.

2024-01-19 05:19 UTC, jzuniga-amd approved these changes
LGTM

2024-02-01 18:53 UTC, qjojo approved these changes

2024-02-01 19:22 UTC, cgmb approved these changes
Trivial comment. LGTM.

2024-02-01 19:22 UTC, cgmb commented on clients/include/testing_stedcj.hpp
> +    int lgn = floor(log(n - 1) / log(2)) + 1;
We should really make a helper function for this operation, as this has shown up a couple times now.

2024-02-02 01:20 UTC, EdDAzevedo commented on clients/include/testing_stedcj.hpp
> +    int lgn = floor(log(n - 1) / log(2)) + 1;
I think there is a log2() function in <cmath>. You can also ask AI to generate a function to compute  the next power of 2 using bit operations.

2024-02-02 18:20 UTC, merged