Added APIs to the rocsolver namespace
ROCmSoftwarePlatform/rocSOLVER pull request #686
Opened 2024-03-08 16:24 UTC by jibrealkhan

2024-03-20 17:20 UTC, cgmb requested changes
Thanks Jibreal. I think there are a couple tweaks required, but it generally looks good.

2024-03-20 17:20 UTC, cgmb commented on clients/include/clientcommon.hpp
> +using namespace rocsolver;
Please ensure that all source files end with a newline.

2024-03-20 17:20 UTC, cgmb commented on common/include/rocblas_utility.hpp
> +    inline namespace v3_26_0{
This is good, but it could be improved by using the macros from rocsolver-version for these numbers.

2024-03-20 17:38 UTC, cgmb commented on common/include/common_host_helpers.hpp
> +ROCSOLVER_BEGIN_NAMESPACE
Oh. I suppose that this header defines functions both within the library and the clients. The rocsolver namespace (especially with the version number) should only be used for functions defined within the library. The `ROCSOLVER_BEGIN_NAMESPACE` should probably be guarded within `#ifdef ROCSOLVER_LIBRARY` to ensure that it's only applied when using this header in library code.

2024-03-20 17:53 UTC, cgmb commented on common/include/common_host_helpers.hpp
> +ROCSOLVER_BEGIN_NAMESPACE
That will make the `using namespace rocsolver;` in `clientscommon.hpp` unnecessary, as neither the rocsolver public API nor any client functions would be in the rocsolver namespace.

2024-04-17 17:46 UTC, tfalders approved these changes
There are some changes I'd like to make to the newlines for better visual consistency, but that's entirely cosmetic and not needed ATM.

2024-04-17 17:46 UTC, tfalders commented on common/include/rocblas_utility.hpp
> +    inline namespace ROCSOLVER_CONCAT4(v, ROCSOLVER_VERSION_MAJOR, ROCSOLVER_VERSION_MINOR_PADDED, ROCSOLVER_VERSION_PATCH_PADDED) {
Minor question, but will this have the periods between the major/minor/patch numbers? I.e. Will it be 3.26.abcde vs 326abcde?

2024-04-17 20:49 UTC, cgmb commented on common/include/rocblas_utility.hpp
> +    inline namespace ROCSOLVER_CONCAT4(v, ROCSOLVER_VERSION_MAJOR, ROCSOLVER_VERSION_MINOR_PADDED, ROCSOLVER_VERSION_PATCH_PADDED) {
No. It needs to be a valid C identifier, so it must start with a letter and can only include alphanumeric characters or underscore. The current inline namespace name is `v32600`, where 3 is the major version, 26 is the minor version and 00 is the patch version.

2024-04-17 21:03 UTC, cgmb commented on common/include/rocblas_utility.hpp
> +    inline namespace ROCSOLVER_CONCAT4(v, ROCSOLVER_VERSION_MAJOR, ROCSOLVER_VERSION_MINOR_PADDED, ROCSOLVER_VERSION_PATCH_PADDED) {
At our current pace, we could reach minor version 100 in ~12 years if we don't make any breaking API changes. However, this is an internal implementation detail, so we can always change the pattern if it becomes a problem. I've tried to keep it compact so it can be easily ignored when browsing through big lists of symbol names.

2024-04-18 19:03 UTC, jzuniga-amd reviewed
LGTM but there are some files with conflicts (maybe just whitespace or stuff like this?)

2024-04-18 20:46 UTC, cgmb commented
> LGTM but there are some files with conflicts (maybe just whitespace or stuff like this?)

There are more issues than whitespace, unfortunately. _All_ library functions should be going into the namespace, except:
1. Functions that are purposely inserted into another library's namespace (e.g., fmt print specializations).
2. The rocsolver C API functions.

No client functions should go into the namespace. The namespace is just for the library, so there should be no changes to the clients.

That means I need to extend this pattern to the new functions added in 6.2 (which is trivial), but as I've been applying my suggestions above, it has revealed that there are functions not being included in the namespace that should be. I'll have to adjust the BEGIN/END for a number of files.

2024-04-24 17:50 UTC, tfalders commented
We should probably retarget this to release-staging, along with the hipSOLVER PR, and merge back to develop afterwards.

2024-04-30 20:56 UTC, cgmb approved these changes
We can do some cleanup later, but it is now functionally complete.

2024-05-02 05:23 UTC, merged