Add 64-bit version of geqrf, geqr2
ROCmSoftwarePlatform/rocSOLVER pull request #767
Opened 2024-07-22 20:09 UTC by qjojo

Adds 64-bit API support to geqr2 and geqrf along with their strided and batched variants.

2024-07-23 01:31 UTC, tfalders requested changes
Looking good so far, but I think you missed geqr2_batched.cpp, geqr2_strided_batched.cpp, geqrf_batched.cpp, and geqrf_ptr_batched.cpp.

2024-07-23 01:31 UTC, tfalders commented on library/src/lapack/roclapack_geqrf.cpp
> +    I shiftA = 0;
Should be rocblas_stride

2024-07-29 20:25 UTC, qjojo commented
Fixed some missing exports and added guards to allow building without the 64-bit API.

2024-07-29 20:41 UTC, tfalders approved these changes
Looks good!

2024-07-30 00:23 UTC, jzuniga-amd approved these changes
LGTM

2024-07-30 04:05 UTC, EdDAzevedo approved these changes

2024-07-31 17:01 UTC, qjojo commented
Since the failures are known and unrelated I will manually merge this.

2024-07-31 17:01 UTC, merged