Add functionality to print hashes and computed errors in tests
ROCmSoftwarePlatform/rocSOLVER pull request #778
Opened 2024-08-02 20:19 UTC by jmachado-amd

rocSOLVER's tests currently output no useful information for passing tests, which makes it hard to ascertain when new code adversely affects the accuracy of methods while also hindering the investigation of bugs that may affect determinism.

This PR adds code to print the computed error in each test and hashing functions to allow printing hashes of input and output matrices, when desired.

2024-08-03 16:02 UTC, EdDAzevedo approved these changes
The std::hash may be implementation dependent. One may consider another hash function such as the following (found using edge browser) to make this more portable across OS and compiler versions. Just a suggestion.

unsigned hash(const char* s, unsigned salt) {
    unsigned h = salt;
    while (*s)
        h = h * 101 + static_cast<unsigned>(*s++);
    return h;
}

2024-08-28 18:42 UTC, cgmb requested changes
I would like to be able to control this behaviour at runtime. Could we control this with an environment variable, rather than a preprocessor flag?

2024-08-28 18:42 UTC, cgmb commented on clients/common/misc/rocsolver_test.hpp
> +#define ANSI_CODE_NORMAL_TERM "\033[0;0m"
If we're going to print with colour, we should follow Google Test's lead by obeying [the gtest_color option](https://google.github.io/googletest/advanced.html#colored-terminal-output) and using TTY detection for the default. I'd suggest printing without colour for now, as that is a bit of a distraction from the main purpose of this change.

2024-08-28 18:42 UTC, cgmb commented on clients/common/misc/rocsolver_test.hpp
> +#define ANSI_CODE_NORMAL_TERM "\033[0;0m"
Also, the fmtlib that we use in rocsolver has a color API. https://fmt.dev/11.0/api/#color-api

2024-08-28 18:42 UTC, cgmb commented on clients/common/misc/rocsolver_test.hpp
> +    std::cout << ANSI_CODE_GTEST_GREEN << "[          ] " << ANSI_CODE_NORMAL_TERM
Use fmt. We added it as a dependency to do atomic prints and avoid the iostreams interfaces where the printing of a line may be split into multiple function calls. It's not that important at the moment, but it's an invariant we inherited from rocfft / rocblas and I want to retain it in case we do ever run tests in parallel.

2024-08-28 18:42 UTC, cgmb commented on clients/common/misc/rocsolver_test.hpp
> +            << std::flush;                                                              \
This would be so much nicer using the fmtlib interface.

2024-08-28 18:42 UTC, cgmb commented on clients/common/lapack/testing_sygvx_hegvx.hpp
> +            [[maybe_unused]] volatile auto mptr = memset(hB[b], 0, n * ldb * sizeof(T));
I assume the `volatile auto mptr` is an attempt to ensure that memset is not optimized out, but I'm not sure that's guaranteed. Why is this needed?

2024-08-28 18:42 UTC, cgmb commented on clients/common/lapack/testing_sygvx_hegvx.hpp
> +                                << std::flush;
`std::endl` is defined as a newline and a flush, so this is redundant. Although, again, I would suggest using fmt rather than iostreams.

2025-07-28 20:32 UTC, closed without merging