Cherry pick to rocm-rel-6.3: Fix some links to the rocBLAS memory alloc API (#803)
ROCmSoftwarePlatform/rocSOLVER pull request #807
Opened 2024-08-29 18:00 UTC by amd-jnovotny

* Fix some links to the rocBLAS memory alloc API

* Wording changes

2024-09-06 20:06 UTC, samjwu approved these changes

2024-09-07 05:18 UTC, cgmb requested changes
The `release/rocm-rel-6.3` branch was created incorrectly. Please target `release-staging/rocm-rel-6.3` as it will soon be forced-pushed over `release/rocm-rel-6.3`.

2024-09-09 12:33 UTC, amd-jnovotny commented
@cgmb I've now created https://github.com/ROCm/rocSOLVER/pull/816 for the fix. I'll close this PR as it seems it is not required. Please let me know if I've misunderstood anything. Thanks!

2024-09-09 12:34 UTC, closed without merging

2024-09-09 12:34 UTC, amd-jnovotny commented
Closed in favor of https://github.com/ROCm/rocSOLVER/pull/816