Fixed broken link
ROCmSoftwarePlatform/rocSOLVER pull request #817
Opened 2024-09-09 16:31 UTC by spolifroni-amd

2024-09-09 21:43 UTC, cgmb approved these changes

2024-09-24 19:17 UTC, samjwu requested changes
I think this should be a cherry pick of https://github.com/ROCm/rocSOLVER/pull/813

2024-09-24 20:54 UTC, spolifroni-amd commented
> I think this should be a cherry pick of #813

It is a cherry pick of 813

2024-09-24 22:20 UTC, samjwu commented
> > I think this should be a cherry pick of #813
> 
> It is a cherry pick of 813

I meant of the squashed merge commit [514a07e](https://github.com/ROCm/rocSOLVER/commit/514a07e7459c0bb3e64a3d76547d3b2f8b34c887).

2024-09-25 19:39 UTC, closed without merging