Enable hashing output for sygvdx
ROCmSoftwarePlatform/rocSOLVER pull request #854
Opened 2024-11-18 21:50 UTC by qjojo

This adds a --hash option to rocsolver-bench which will use a deterministic hash function on the outputs and print the result. This is for testing bitwise reproducibility across machines and runs.

2024-11-18 23:21 UTC, tfalders requested changes

2024-11-18 23:21 UTC, tfalders commented on clients/benchmarks/client.cpp
> +        ("hash",
A newline between hash and the previous argument would be appreciated

2024-11-18 23:21 UTC, tfalders commented on clients/common/lapack/testing_sygvdx_hegvdx.hpp
> +        if(argus.hash_check)
Correct me if I'm wrong, but won't getPerfData overwrite hA before we reach this point? You might want to put this directly after getError so that the output matrices aren't overwritten.

2024-11-19 04:27 UTC, tfalders approved these changes

2024-11-19 21:08 UTC, jmachado-amd reviewed
Just a few comments here, so that we can discuss.

2024-11-19 21:08 UTC, jmachado-amd commented on clients/common/lapack/testing_sygvdx_hegvdx.hpp
> +
I am unsure whether this is accomplishing what it is supposed to, but I understand the necessity of moving forward and fixing possible issues later.

For the hash of the input (`hashA`), lapacks' `sygvx` always destroys the contents of matrix `hA`, and the current implementation of `sygvdx_hegvdx_getError` also uses `hA` as part of the computation of the error. I think you want to use the matrix `hA` as produced by `sygvdx_hegvdx_initData`, which will require some changes to this code: maybe call the `initData` method again here? Moreover, for rocsolver's `sygvx` and `sygvdx` tests you should hash both of the original matrices `hA` and `hB`, as `sygvdx_hegvdx_initData` uses other lapack methods to produce `hB` and this yields observable changes to rocsolver's output.

Similarly, for the hash of the output (`hashZ`), it should include the eigenvalues as well (matrix `hWRes`) instead of just the eigenvectors.

2024-11-19 21:08 UTC, jmachado-amd commented on clients/common/misc/rocsolver_test.hpp
> +/// from an array). Values will be the same across implementations and executions.
This is not correct as written, `hash_combine` is deterministic but the values it produces can vary across implementations and even executions -- this is why it is important to provide hashes for both the input and the output.

If a _reproducible_ version is desired, then we will need more work.

2024-11-19 21:08 UTC, jmachado-amd commented on clients/common/misc/rocsolver_test.hpp
> +    return hash_combine(1, vector.data(), vector.size());
Very minor, if you have a chance, please cast `1` to `std::size_t` to prevent compiler warnings due to type mismatch.

2024-11-19 21:08 UTC, jmachado-amd commented on clients/benchmarks/client.cpp
> +            "                           Hash values are deterministic across implementations and executions.\n"
Hash values are deterministic, but they can change across implementations and executions.

2024-11-20 01:16 UTC, qjojo commented
Added checks for getrf, potrf, syevx, sygvx, updated the checks on sygvdx, and updated comments.

2024-11-20 01:41 UTC, jzuniga-amd approved these changes
LGTM

2024-11-20 15:22 UTC, qjojo commented
CI failures are known issues with sygvdx unrelated to this PR, merging.

2024-11-20 15:22 UTC, merged